### ISSUE TITLE
number of cores used in pipeline

### ISSUE THREAD

**Issue by Sekomer** [neuralmagic/deepsparse#1007]
**Describe the bug**
I set num_cores parameter to max (seems default value None does that too), but pipeline only uses 32 cores

**Expected behavior**
I'd expect that to use all 64 cores in my machine

**Environment**
Include all relevant environment information:
1. OS Ubuntu 20.04
2. Python version 3.8
3. DeepSparse version 1.4.2
4. ML framework version(s) torch: '2.0.0+cu117'
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
{'L1_data_cache_size': 32768, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 1048576, 'L3_cache_size': 23068672, 'architecture': 'x86_64', 'available_cores_per_socket': 16, 'available_num_cores': 32, 'available_num_hw_threads': 64, 'available_num_numa': 2, 'available_num_sockets': 2, 'available_sockets': 2, 'available_threads_per_core': 2, 'bf16': False, 'cores_per_socket': 16, 'dotprod': False, 'i8mm': False, 'isa': 'avx512', 'num_cores': 32, 'num_hw_threads': 64, 'num_numa': 2, 'num_sockets': 2, 'threads_per_core': 2, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': 'Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz', 'vnni': True}
```

**To Reproduce**
```python
import os
import time
import numpy as np
from deepsparse import Pipeline

model_path = os.path.join(os.getcwd(), 'yolov8x.onnx')
images = 32 * ['basilica.jpg']

yolo_pipeline = Pipeline.create(
    task="yolo",
    model_path=model_path,
    num_cores=64
)       

while True:
    s = time.perf_counter()
    pipeline_outputs = yolo_pipeline(images=images)
    print(pipeline_outputs)
    print(f'fps: {1/ (time.perf_counter() - s)}')
```

**Comment by rsnm2** [comment]
Can you share the output of lscpu?

My suspicion is that your machine has 64 threads and 32 cores

For instance, here is the output of lscpu on an 8 core Ice Lake:

CPU(s):                                16
On-line CPU(s) list:             0-15
Thread(s) per core:             2
Core(s) per socket:             8
Socket(s):                             1

**Comment by Sekomer** [comment]
I see that now, it's based on cores instead of hyper-threads, but why? Wouldn't using all the CPU increase the performance?

**Comment by Sekomer** [comment]
thank you!
