### ISSUE TITLE
pruned/quantized yolov8 model is slower

### ISSUE THREAD

**Issue by denguir** [neuralmagic/deepsparse#1028]
Hi there,

I've come across this repo today and I was trying to observe the effect of pruning/quantization on YOLOv8 model performance. So following the instrucstions [here](https://github.com/neuralmagic/deepsparse/tree/main/src/deepsparse/yolov8), I performed two benchmarks:
- the first one is on the pruned & quantized model **yolov8n_quant.onnx** that I downloaded  [here](https://drive.google.com/drive/folders/1vf4Es-8bxhx348TzzfhvljMQUo62XhQ4). Here is the result:
![image](https://github.com/neuralmagic/deepsparse/assets/15349453/2d9a4715-da92-457c-9c44-e1c859ee9b9a)

- the second one is on the  model **yolov8n.onnx* that I exported directly from ultralytics model registry using the command:
```shell
yolo export model=yolov8n.pt imgsz=640 format=onnx opset=13
```
Here is the result:
![image](https://github.com/neuralmagic/deepsparse/assets/15349453/d048c20f-44a8-43ec-ba9b-a2e8a0b762fb)

I didn't expect to have a drop in throughput / latency. Maybe I am not comparing it correctly ?
Here are my CPU info:
```python
>>> pp.pprint(deepsparse.cpu.cpu_architecture())
{   'L1_data_cache_size': 32768,
    'L1_instruction_cache_size': 65536,
    'L2_cache_size': 524288,
    'L3_cache_size': 8388608,
    'architecture': 'x86_64',
    'available_cores_per_socket': 8,
    'available_num_cores': 8,
    'available_num_hw_threads': 16,
    'available_num_numa': 1,
    'available_num_sockets': 1,
    'available_sockets': 1,
    'available_threads_per_core': 2,
    'bf16': False,
    'cores_per_socket': 8,
    'dotprod': False,
    'i8mm': False,
    'isa': 'avx2',
    'num_cores': 8,
    'num_hw_threads': 16,
    'num_numa': 1,
    'num_sockets': 1,
    'threads_per_core': 2,
    'vendor': 'AuthenticAMD',
    'vendor_id': 'AMD',
    'vendor_model': 'AMD Ryzen 7 2700X Eight-Core Processor',
    'vnni': False}
>>> 
```

Thanks

**Comment by tlrmchlsmth** [comment]
Hi @denguir, the first thing I notice is that the model you linked appears to be a _dense_ quantized model, not pruned. Your avx2 machine doesn't support VNNI instructions, so speedup may be limited in this case.  We're still working on improving the performance of yolov8 in the engine -- On 8 cores of my AMD EPYC 7713, I'm seeing a performance improvement in the engine of about 15% on the model that you linked between DeepSparse 1.4.2 and the release candidate for 1.5. So you may be interested in installing `deepsparse-nightly` and seeing the performance there as well.
