### ISSUE TITLE
Build instructions for other CPU architectures

### ISSUE THREAD

**Issue by mgiessing** [neuralmagic/deepsparse#1077]
**Describe the bug**
I'm trying to install/build for currently unsupprted CPU architecture - do you have instructions on how to achieve that?

**Environment**
Include all relevant environment information:
1. OS: RHEL9.1
2. Python version [e.g. 3.8]: 3.10
3. DeepSparse version: 1.5.0

**Additional context**
I'm trying to build for ppc64le arch which is CPU-only, but it has Matrix-math accelerator engines on the core which is aimed for ML & DL inference.

**Comment by mgoin** [comment]
Hi @mgiessing we're currently working on aarch64 support and are in alpha for that. We keep the core implementation of the engine closed-source so we have to support those new platforms ourselves. We aren't considering PowerPC at the moment since it isn't as widely used as ARM. Thanks for asking!
