### ISSUE TITLE
Neural Magic: Encountered exception while trying to read arch.bin: Unable to determine instruction set

### ISSUE THREAD

**Issue by aymeric75** [neuralmagic/deepsparse#1079]
Hello,

I am on LInux MInt 20 (Ubuntu 20), and I want to use the open-cv VIdeoCapture and a YOLO model to make inference on  a video. I also want to use a sparsified version of the yolo model, in order to have a fast inference.

But, I barely coded this:

```
import cv2
from ultralytics import YOLO
from deepsparse import Pipeline

model_stub = "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned65_quant-none"

yolo_pipeline = Pipeline.create(
    task="yolo",
    model_path=model_stub,
)

```

And I already have an error:

Traceback (most recent call last):
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/cpu.py", line 132, in _parse_arch_bin
    info_str = subprocess.check_output(file_path).decode("utf-8")
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/arch.bin' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:
```

Traceback (most recent call last):
  File "/home/random/Bureau/BOWLING/main.py", line 3, in <module>
    from deepsparse import Pipeline
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/__init__.py", line 33, in <module>
    from .engine import *
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/engine.py", line 28, in <module>
    from deepsparse.benchmark import BenchmarkResults
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/benchmark/__init__.py", line 19, in <module>
    from .ort_engine import *
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/benchmark/ort_engine.py", line 52, in <module>
    ARCH = cpu_architecture()
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/cpu.py", line 163, in cpu_architecture
    arch = _parse_arch_bin()
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/cpu.py", line 51, in __call__
    self.memo[args] = self.f(*args)
  File "/home/random/anaconda3/envs/yolo5/lib/python3.9/site-packages/deepsparse/cpu.py", line 137, in _parse_arch_bin
    raise OSError(error_msg.format(error["error"]))
OSError: Neural Magic: Encountered exception while trying to read arch.bin: Unable to determine instruction set.
```

Any idea?

Thanks

**Comment by tlrmchlsmth** [comment]
Hi @aymeric75, to help us figure out what's going on, we'd like more information about the system that you're running on. Could you share the output of `lscpu` or `cat /proc/cpuinfo`? This will let us know more about the hardware that you're running on. Are you running in a virtual machine?

**Comment by aymeric75** [comment]
Hello and thanks for the help, here is the output

Architecture :                          x86_64
Mode(s) opératoire(s) des processeurs : 32-bit, 64-bit
Boutisme :                              Little Endian
Address sizes:                          39 bits physical, 48 bits virtual
Processeur(s) :                         4
Liste de processeur(s) en ligne :       0-3
Thread(s) par cœur :                    1
Cœur(s) par socket :                    4
Socket(s) :                             1
Nœud(s) NUMA :                          1
Identifiant constructeur :              GenuineIntel
Famille de processeur :                 6
Modèle :                                122
Nom de modèle :                         Intel(R) Pentium(R) Silver N5030 CPU @ 1
                                        .10GHz
Révision :                              8
Vitesse du processeur en MHz :          1102.626
Vitesse maximale du processeur en MHz : 3100,0000
Vitesse minimale du processeur en MHz : 800,0000
BogoMIPS :                              2188.80
Virtualisation :                        VT-x
Cache L1d :                             96 KiB
Cache L1i :                             128 KiB
Cache L2 :                              4 MiB
Nœud NUMA 0 de processeur(s) :          0-3
Vulnerability Itlb multihit:            Not affected
Vulnerability L1tf:                     Not affected
Vulnerability Mds:                      Not affected
Vulnerability Meltdown:                 Not affected
Vulnerability Mmio stale data:          Not affected
Vulnerability Spec store bypass:        Mitigation; Speculative Store Bypass dis
                                        abled via prctl and seccomp
Vulnerability Spectre v1:               Mitigation; usercopy/swapgs barriers and
                                         __user pointer sanitization
Vulnerability Spectre v2:               Mitigation; Enhanced IBRS, IBPB conditio
                                        nal, RSB filling
Vulnerability Srbds:                    Not affected
Vulnerability Tsx async abort:          Not affected
Drapaux :                               fpu vme de pse tsc msr pae mce cx8 apic 
                                        sep mtrr pge mca cmov pat pse36 clflush 
                                        dts acpi mmx fxsr sse sse2 ss ht tm pbe 
                                        syscall nx pdpe1gb rdtscp lm constant_ts
                                        c art arch_perfmon pebs bts rep_good nop
                                        l xtopology nonstop_tsc cpuid aperfmperf
                                         tsc_known_freq pni pclmulqdq dtes64 ds_
                                        cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdc
                                        m sse4_1 sse4_2 x2apic movbe popcnt tsc_
                                        deadline_timer aes xsave rdrand lahf_lm 
                                        3dnowprefetch cpuid_fault cat_l2 cdp_l2 
                                        ssbd ibrs ibpb stibp ibrs_enhanced tpr_s
                                        hadow vnmi flexpriority ept vpid ept_ad 
                                        fsgsbase tsc_adjust smep erms mpx rdt_a 
                                        rdseed smap clflushopt intel_pt sha_ni x
                                        saveopt xsavec xgetbv1 xsaves dtherm ida
                                         arat pln pts umip rdpid md_clear arch_c
                                        apabilities

**Comment by tlrmchlsmth** [comment]
Hi @aymeric75, I'm sorry but your CPU is too old to support DeepSparse, as it requires at least the AVX2 instruction set.

**Comment by aymeric75** [comment]
Thanks, would any of the yolo model work on a Raspberry ?
