### ISSUE TITLE
Output is not the same as ONNX

### ISSUE THREAD

**Issue by kopyl** [neuralmagic/deepsparse#1092]
Here is how I run the inference:

```
images = ["image194_212333.jpg"]
>>> def test():
...     s = time.time()
...     res = pipeline_outputs = yolo_pipeline(images=images, iou_thres=0.6, conf_thres=0.001)
...     print(time.time() - s)
...     return res
...
>>> test()
0.18682217597961426
YOLOOutput(boxes=[[[-8.861318664550781, 4.7944226074218745, 37.795638427734374, 57.20454711914062], [-5.396675262451172, 0.6913192749023437, 18.551546630859374, 29.469034423828123], [10.067341918945312, 7.235080261230468, 19.599724731445313, 16.015762939453126], [5.424901428222656, 3.771606903076172, 10.172668762207032, 8.232398071289062]]], scores=[[41968.94140625, 29060.572265625, 4908.19189453125, 3657.376220703125]], labels=[['13055.0', '5894.0', '12846.0', '9911.0']], intermediate_outputs=None)
```

I need to get class ids (or label names), boxes and scores. How can I get them?

With Ultralytic's YOLO it's simple:
```
model = YOLO("model.pt"))
res = model("quIHie6.jpg", conf=0.35)
for result in res:
        boxes = result.boxes
        for box in boxes:
            confidence = box.conf.item()
            name = class_names[int(box.cls.item())]
            print(name, confidence)
```

How can I get human-readable data from the Yolov8 inference on DeepSparce?

**Comment by dbogunowicz** [comment]
Take a look here:
https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/yolo/pipelines.py#L67C17-L67C17
```
:param class_names: Optional string identifier, dict, or json file of
        class names to use for mapping class ids to class labels.
```
So I'd recommend you to pass:
`res = pipeline_outputs = yolo_pipeline(images=images, iou_thres=0.6, conf_thres=0.001, class_names="coco")`
or if your model was not trained on coco:
`res = pipeline_outputs = yolo_pipeline(images=images, iou_thres=0.6, conf_thres=0.001, class_names=labels.json)`
`res = pipeline_outputs = yolo_pipeline(images=images, iou_thres=0.6, conf_thres=0.001, class_names={'label_1', 'label_2', ...})`

**Comment by kopyl** [comment]
@dbogunowicz thanks :)
