### ISSUE TITLE
Support numpy   > 1.21.6

### ISSUE THREAD

**Issue by SmartAudioTools** [neuralmagic/deepsparse#1093]
Hello, 
I would like to be able to use deepsparse with a numpy > 1.21.6 . Is it just a setup.py problem or is there a real incompatibility with numpy > 1.21.6 ?
Thanks

**Comment by dbogunowicz** [comment]
Same answer as here: https://github.com/neuralmagic/sparsezoo/issues/336

**Comment by mgoin** [comment]
Fix has landed! Thanks for bringing it up

**Comment by SmartAudioTools** [comment]
Hello!
I'm still not able to install deepsparse with numpy>=1.22 

ERROR: Cannot install deepsparse and numpy>=1.22 because these package versions have conflicting dependencies.
  
 The conflict is caused by:
     The user requested numpy>=1.22
     deepsparse 1.5.2 depends on numpy>=1.16.3
     onnx 1.12.0 depends on numpy>=1.16.6
     sparsezoo 1.5.2 depends on numpy<=1.21.6 and >=1.0.0
