### ISSUE TITLE
Can't use DeepSparse with VITS ONNX file from Coqui TTS.

### ISSUE THREAD

**Issue by mllopartbsc** [neuralmagic/deepsparse#1147]
Hi,

I was trying to use DeepSparse with this onnx file:

https://drive.google.com/file/d/1mtAqUA_3WRCS2Og9IkBnDg7ciC3CXWH8/view?usp=sharing

The file is save locally in a specific path, and the script I was using to run it for inference was this one:

```
from deepsparse import Engine
from deepsparse.utils import generate_random_inputs
onnx_filepath = "coqui_vits.onnx"
batch_size = 16

# Generate random sample input
inputs = generate_random_inputs(onnx_filepath, batch_size)

# Compile and run
compiled_model = Engine(model=onnx_filepath, batch_size=batch_size)
outputs = compiled_model(inputs)
print(outputs[0].shape)
# (16, 1000) << batch, num_classes
```

This is the error I'm encountering: 

`
RuntimeError: NM: error: Non-zero status code returned while running Conv node. Name:'/text_encoder/encoder/attn_layers.0/conv_q/Conv' Status Message: Invalid input shape: {0}`

I printed the inputs and this is what I was returned:

```
[array([], shape=(16, 0), dtype=int64), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0.5540935 , 0.31644872, 0.20993647, 0.9885486 , 0.58911484,
       0.8773906 , 0.81389457, 0.0729698 , 0.60800195, 0.5848782 ,
       0.96580833, 0.79112357, 0.9744207 , 0.55439687, 0.83145213,
       0.2759266 ], dtype=float32), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]
```

Therefore the generate_random_inputs function is not generating the correct inputs for the onnx model?

How could I fix that? 

Thank you.

**Comment by mgoin** [comment]
Hi @mllopartbsc it looks like the model has dynamic shapes on its inputs so the generate_random_inputs function doesn't have enough information to generate shaped random data for your model. This is why it is producing shapes such as `shape=(16, 0)` which has an empty (0) dimension and won't qualify as good data to pass in.

Here is a picture of the inputs/outputs in Netron. Notice the first input has shape `"[batch_size, phonemes]"`, which means it can be set to any value for those dimensions.
<img width="895" alt="Screenshot 2023-07-27 at 4 15 55 PM" src="https://github.com/neuralmagic/deepsparse/assets/3195154/714994e4-f959-4b29-980a-4b8c339f6c36">

Another wrinkle is that the `scales` input looks to have a constant 3 element input, which might interact with setting the batch size. So you'll probably want to disable automatic batching with the `NM_DISABLE_BATCH_OVERRIDE=1` environment variable and set the input shapes manually in the `Engine` class like `input_shapes=[[1,100],[1],[3],[1]]`

Can you share any more detail how you've exported the model to ONNX or if you have any code using it on data? Just from looking at the graph, it is difficult to know what are valid inputs to it myself.

**Comment by mllopartbsc** [comment]
Hi @mgoin,

Thank you for the prompt response.

This is the function I've used to export the VITS model to ONNX :

https://github.com/coqui-ai/TTS/blob/b739326503b6077c8662c0244b461ca75294384e/TTS/tts/models/vits.py#L1806

And this is the script I've used for that:

```
import numpy as np
import os
import json
import sys
import time
import torch

from pathlib import Path
from TTS.tts.models.vits import Vits
from TTS.tts.configs.vits_config import VitsConfig
from TTS.utils.audio.numpy_transforms import save_wav
from TTS.utils.manage import ModelManager

config = VitsConfig()
config.load_json("config.json")
vits = Vits.init_from_config(config)
vits.load_checkpoint(config,  "model_file.pth")

vits.export_onnx()
vits.load_onnx("coqui_vits.onnx")
```
To reproduce the export you'll need to download [this](https://github.com/coqui-ai/TTS/blob/e5fb0d96279af9dc620add6c2e69992c8abd7f24/TTS/.models.json#L143C17-L143C17) link which contains the config.json and the model_file.pth. Also, you'll need to set the correct path for them.

To test an inference run with the ONNX model you can add the following lines to the  previous code: 

```
text1 = "The field of space exploration has continually fascinated humanity, igniting the collective imagination and driving scientific and technological advancement. From the first successful launch of Sputnik 1 by the USSR in 1957, it became clear that space was a new frontier, ripe for exploration."
text_inputs1 = np.asarray(
    vits.tokenizer.text_to_ids(text1, language="en"),
    dtype=np.int64,
)[None, :]

start = time.time()
audio1 = vits.inference_onnx(text_inputs1)
end = time.time()
print("Inference 1 Time Taken: ", end - start, " seconds")

print(audio1.shape)
save_wav(wav=audio1[0], path="ONNX_1.wav", sample_rate=config.audio.sample_rate)
```
In case you encounter an issue in regards to the sid, you'll have to modify [this](https://github.com/coqui-ai/TTS/blob/b739326503b6077c8662c0244b461ca75294384e/TTS/tts/models/vits.py#L1890) function from the TTS library from Coqui and change it to the following script: 

```
    def inference_onnx(self, x, x_lengths=None):
        """ONNX inference
        """

        if isinstance(x, torch.Tensor):
            print("it is!")
            x = x.cpu().numpy()

        if x_lengths is None:
            x_lengths = np.array([x.shape[1]], dtype=np.int64)

        if isinstance(x_lengths, torch.Tensor):
            x_lengths = x_lengths.cpu().numpy()
        scales = np.array(
            [self.inference_noise_scale, self.length_scale, self.inference_noise_scale_dp],
            dtype=np.float32,
        )
        print(scales)
        audio = self.onnx_sess.run(
            ["output"],
            {
                "input": x,
                "input_lengths": x_lengths,
                "scales": scales,
                "sid": None,
            },
        )
        return audio[0][0]
```

Let me know if this is of any help.

Kind Regards,
Martí Llopart

**Comment by mgoin** [comment]
Hi @mllopartbsc thanks for sharing those edits need for the TTS library! I was able to get a working ONNX export and run through the model like you.

I put those changes in a fork here: https://github.com/mgoin/TTS/tree/patch-1 , see this link for the compare with main https://github.com/coqui-ai/TTS/compare/dev...mgoin:TTS:patch-1

With this model, I was able to make some dummy inputs and construct a DeepSparse Engine around the model. However I did run into an issue on engine compilation related to empty dimensions inside the network, so I'm investigating this bug right now. Here is the script I used to trigger that.
```python
import numpy as np
import os
from deepsparse import Engine

onnx_filepath = "coqui_vits.onnx"

x = np.array([[178,48,178,123,178,138,178,55,178,81,178,83,178,16,178,44,178,102,178,92,178,156,178,102,178,56,178,102,178,112]])
x_lengths = np.array([30])
scales = np.array([1.,1.,1.], dtype=np.float32)

# Assemble the inputs to a list
inputs = [x, x_lengths, scales]  

# Compile and run
os.environ["NM_DISABLE_BATCH_OVERRIDE"] = "1"
input_shapes = [list(i.shape) for i in inputs]
compiled_model = Engine(model=onnx_filepath, input_shapes=input_shapes)

outputs = compiled_model.run(inputs, val_inp=False)

print(outputs[0].shape)
```

**Comment by mllopartbsc** [comment]
Hi @mgoin, 

I appreciate the efforts, could you share the exact error you are encountering?

Kind Regards

**Comment by mgoin** [comment]
Hi @mllopartbsc I have a candidate fix so the model can run with the above script. It should hopefully be accepted and land in the `deepsparse-nightly` package in a few days - I will reach out here to let you know when it is ready for you.

As for what performance gain you'll be able to gain, I have doubts since there are several operations in the network that DeepSparse is not optimized for. Here is a screenshot of the ONNX graph where you can see there are many GatherND, ScaterND, and GatherElements operations present in the network. DeepSparse doesn't have efficient implementations of these operations so much of the network will be running in a naive path. I'm not sure you'll see a large benefit over how you are currently running the model, even with quantization because of all these non-Conv or Gemm operations
<img width="873" alt="Screenshot 2023-08-09 at 6 07 31 PM" src="https://github.com/neuralmagic/deepsparse/assets/3195154/6079a5e7-26be-46a3-a21a-7d7a2889e01b">

**Comment by mllopartbsc** [comment]
Hi @mgoin thank you so much for your efforts, I'll be checking out the update.

Kind Regards.

**Comment by mgoin** [comment]
Hi @mllopartbsc the latest nightly has the fixes, thanks for your patience! Just do `pip install -U deepsparse-nightly` and try running the script I shared above. It worked tested on my machine but let me know if you see anything strange

**Comment by mllopartbsc** [comment]
Hi @mgoin, thanks a lot for your efforts, it works like a charm! 

Closing the issue now.

**Comment by mllopartbsc** [comment]
Hi @mgoin, thanks a lot for your efforts, it works like a charm!

Closing the issue now.

**Comment by Nanayeb34** [comment]
@mgoin @mllopartbsc the vits models you converted to ONNX, was it a single speaker model or a multi speaker model?

**Comment by mllopartbsc** [comment]
Hi @Nanayeb34, it was a single speaker model which you can find [here](https://github.com/coqui-ai/TTS/blob/e5fb0d96279af9dc620add6c2e69992c8abd7f24/TTS/.models.json#L143C17-L143C17).
