### ISSUE TITLE
How to use Benchmark feature on custom dataset

### ISSUE THREAD

**Issue by atultiwari** [neuralmagic/deepsparse#1256]
Hi,
First of all thank you very much for this awesome project. I wanted to try it out for research purpose to compare its effectiveness with respect to GPU. I am trying to do this on custom dataset. This dataset has 10 classes. So there is folder named Dataset, in that there are two folders - Train & Test. In both of those there are 10 classes and each class has 200 images. Now I want to use benchmark on how much time does Yolo v8 take on CPU & on GPU, and how much time does Deepsparse takes. But I am unable to find any solution for that. Can you please guide me. thank you

**Comment by Satrat** [comment]
Hi @atultiwari, DeepSparse has built-in benchmarking you can invoke with `deepsparse.benchmark_pipeline` that will allow you to pass in custom input data. See the [benchmark README](https://github.com/neuralmagic/deepsparse/tree/main/src/deepsparse/benchmark#-benchmarking-pipelines) for full instructions
