### ISSUE TITLE
Does he support stable diffusion or fooocus, or other image generation acceleration?

### ISSUE THREAD

**Issue by libai-lab** [neuralmagic/deepsparse#1339]
Does he support stable diffusion or fooocus, or other image generation acceleration?If so, how can I use it? Is there a tutorial?

**Comment by jeanniefinks** [comment]
Hi @libai-lab 
DeepSparse can technically run stable diffusion. However, optimization benefits and additional robust support for image generation models would be potentially on a longer-term roadmap and not in the near- or medium-term. We are focusing on a subset of LLMs and will have exciting news to share by the end of the year.

I will archive your message and note it for reference as we plan our future roadmaps. Thank you!
Jeannie / Neural Magic
