### ISSUE TITLE
Grrrrrrr

### ISSUE THREAD

**Issue by WeurnomboTroc** [neuralmagic/deepsparse#1349]
**What is the URL, file, or UI containing proposed doc change**
Where does one find the original content or where would this change go?

**What is the current content or situation in question**
Copy/paste the source content or describe gap.

**What is the proposed change**
Add new content.

**Additional context**
Add any other context about the change here. Also include any relevant files or URLs.

**Comment by jeanniefinks** [comment]
Hi @WeurnomboTroc 
If you have a specific document change in mind, please let us know. I'll close this issue, but feel free to reopen as needed.
Thank you, Jeannie // Neural Magic

**Comment by WeurnomboTroc** [comment]
@

**Comment by WeurnomboTroc** [comment]
Au DD.

**Comment by WeurnomboTroc** [comment]
King
