### ISSUE TITLE
https://www.therapyinsightspractice.com

### ISSUE THREAD

**Issue by Mjsmiles23** [neuralmagic/deepsparse#1360]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mgoin** [comment]
Hi @Mjsmiles23 unfortunately that therapy website doesn't seem directly related to deepsparse :) 
Closing this as unrelated but let me know if you have suggested enhancements!
