### ISSUE TITLE
Adding Contributors Section to readme.md

### ISSUE THREAD

**Issue by mohitd404** [neuralmagic/deepsparse#1361]
**What is the URL, file, or UI containing proposed doc change**
Where does one find the original content or where would this change go?

Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

**What is the proposed change**
![3](https://github.com/neuralmagic/deepsparse/assets/146939900/89603ab1-7f3a-4b4f-b861-25cfd8634386)

**Additional context**

@mgoin @horheynm  kindly assign this issue to me ! I would love to work on it ! Thank you !

**Comment by mgoin** [comment]
@mohitd404 this is a great idea! Thanks for the thought and contribution
