### ISSUE TITLE
Does a C API exist for deepsparse or is this python only and are all benchmarks via python?

### ISSUE THREAD

**Issue by nietras** [neuralmagic/deepsparse#174]
Just a quick question. Is it possible to use deepsparse for inference directly in other languages e.g. C++, C# or similar? Or is all code written in python?

**Comment by bnellnm** [comment]
Currently, we only have a python interface but we are planning on adding a C++ interface in an upcoming release.

**Comment by fwsGonzo** [comment]
Will you be able to produce a static binary in the upcoming release? Python is notoriously hard to embed statically, and it would be nice to hear if you have any plans on producing a C++-only version.

**Comment by bnellnm** [comment]
@fwsGonzo , we plan on providing a library to generate standalone C++ applications (no python involved).  At first It will still probably have some basic shared library dependencies, e.g. libc, libdl, etc. similar to python's manylinux restrictions.

**Comment by jeanniefinks** [comment]
Hi @fwsGonzo 
I am happy to report this was included in our last release; please check out the documentation here, thanks!
[https://docs.neuralmagic.com/deepsparse/main/source/c%2B%2Bapi-overview.html](https://docs.neuralmagic.com/deepsparse/main/source/c%2B%2Bapi-overview.html )

**Comment by nietras** [comment]
@jeanniefinks the API in question is an C++ API, which of course is good, but the question here is for a `C` API, one that can be used from other languages Java, C# (p/invoke) etc. So would not say this closes this issue. The issue is not C++ it's how to use deepsparse easily from C# for example, by calling C methods on a dynamic link library or shared object. One can, of course, create that by creating a C API wrapper around C++ ourselves, but that seems redundant. As an example one could look a the C API for the ONNX Runtime. https://github.com/microsoft/onnxruntime/blob/master/docs/C_API_Guidelines.md

**Comment by hardsetting** [comment]
@jeanniefinks thanks for adding the C++ API!
I tried looking around for the source code of the API (for testing with cross-compiling) but couldn't find it anywhere.
Is there any plan to release it too?

**Comment by jeanniefinks** [comment]
@nietras 
At this time, there are no plans for Neural Magic for the inclusion of a `C` API. Our internal team though has been made aware of this thread should there be a change on our roadmap.

@hardsetting 
Because the API is within our binary for the DeepSparse Engine, we cannot distribute the source code of the API. However, on the documentation page ([https://docs.neuralmagic.com/deepsparse/main/source/c%2B%2Bapi-overview.html](https://docs.neuralmagic.com/deepsparse/main/source/c%2B%2Bapi-overview.html)) there is a demo we encourage you to look at if not already that may provide some clarity.

Best, Jeannie / Neural Magic

**Comment by jeanniefinks** [comment]
Hello @nietras and @hardsetting 
As it's been a few weeks with no response, I am going to close this thread. But please do re-open if you have additional related questions; we're happy to help.

Best, Jeannie / Neural Magic

**Comment by Y-T-G** [comment]
@jeanniefinks 

Is this C++ API still up to date? Will I get the same performance as latest Python version if I use the `libdeepsparse` that comes with the demo API?
