### ISSUE TITLE
Deepsparse BERT Classification model.

### ISSUE THREAD

**Issue by subhasisj** [neuralmagic/deepsparse#178]
I want to convert a BERT classification model twith Deepsparse. I'm unable to find any appropriate examples for the. 

I have an ONNX converted a model fine tuned with Hugging face API. 
Any help with this regard is highly appreciated.

Thanks,
Subhasis

**Comment by markurtz** [comment]
Hi @subhasisj, are there any current issues you're running into? If you have an ONNX exported from the Hugging Face API, then you should be able to measure performance with that by simply plugging the DeepSparse API into your current pipeline. Some examples specifically for Hugging Face can be found [here](https://github.com/neuralmagic/deepsparse/tree/main/examples/huggingface-transformers).

If you're looking for sparsified speedup with furder compression and speedup over that, then we would recommend following the SparseML tutorial to create a pruned and potentially layer-dropped model for inference [here](https://github.com/neuralmagic/sparseml).

Thanks and let me know if you have any further questions!

**Comment by subhasisj** [comment]
Hi Mark,
Thanks for replying. I want to leverage sparsification for improved inference speeds with my BERT Model for a text classification task.
https://github.com/neuralmagic/sparseml/blob/main/integrations/huggingface-transformers/tutorials/sparsifying_bert_using_recipes.md

The above link talks about SQuAD dataset and shows how to use it with run_qa.py script. But can I use the same for a text classification ? Is there any adapted script that I can reuse for text classification models ?

**Comment by markurtz** [comment]
Yes, great question. We have a branch up on our transformers fork that you can try out which includes a GLUE example using our recipes located here: https://github.com/neuralmagic/transformers/blob/50277cb780535ee9106a456b84ef00d90a91ce36/examples/pytorch/text-classification/run_glue.py#L75

We're planning to land this soon and have example recipes up for it, but in the meantime, you can follow the tutorial for SQuAD and adapt to this code pathway. Specifically after running the setup_integration.sh here: https://github.com/neuralmagic/sparseml/tree/main/integrations/huggingface-transformers cd into the transformers directory and then run `git checkout sparsify_all_examples` to switch over to this newer code. 

Let us know if you have any issues and more than happy to chat through our slack community to go more in-depth for your use case!

Mark

**Comment by jeanniefinks** [comment]
Hi @subhasisj 
Thank you for your feedback. We're looking at doing Colab notebooks for these examples for sure. If you would to stay in touch on these types of activities, go to [Neural Magic Contact Us page](https://neuralmagic.com/contact/) and subscribe to the email communications from this page. We don't sell your info and it's not a lot of emails - we don't want to drive our users crazy. If there are no more other questions, I'll close this issue. But please re-open if something comes to mind or start a new issue on a new topic. 

Happy Monday.
Jeannie / Neural Magic
