### ISSUE TITLE
Is there plan to support sparse NN influence on mobile devices, such as Arm CPUs? 

### ISSUE THREAD

**Issue by stonextu** [neuralmagic/deepsparse#183]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by markurtz** [comment]
Hi @stonextu, it's definitely a requested feature and we have looked into it. Based on the amount of work for support, it's on our medium to long-term roadmap currently. Subscribe to our email list or join our slack community to receive updates for this and any changes in priorities! Additionally, as we push closer to official support we'll be looking for alpha and beta testers.

**Comment by stonextu** [comment]
Sure, already subscribed. Looking forwards to seeing it. 

In addition, I noticed that NeuralMagic don't open source onnx-deepsparse-runtime instead of .so file.  Will open source  onnx-deepsparse-runtime later?

**Comment by markurtz** [comment]
Great to hear you're already subscribed! Open sourcing of the backend runtime is something we're not planning for the near to medium term. It is something we're actively reevaluating, though, as the company and the industry as a whole grows to see what works best for the needs of our users.

**Comment by mgoin** [comment]
Closing as this is not a short-term issue/target and discussion has fizzled. Thanks!
