### ISSUE TITLE
How to derive the probability of the predictions in deepsparse? For classification for example

### ISSUE THREAD

**Issue by pacospace** [neuralmagic/deepsparse#187]
**Additional context**
Related-To: https://github.com/AICoE/elyra-aidevsecops-tutorial/issues/297

**Comment by jeanniefinks** [comment]
Hello @pacospace 
Just checking in to see if you were able to provide more details or we should close out this issue? Thank you!
Best, Jeannie / Neural Magic

**Comment by pacospace** [comment]
@markurtz @jeanniefinks I'm sorry for late reply!! This definetly answer my question, so my changes needs to be adjusted on the ONNX graph!
