### ISSUE TITLE
Can deepsparse run on windows 10?

### ISSUE THREAD

**Issue by gkomix88** [neuralmagic/deepsparse#191]
Hi, I would like to try deepsparse with yolov5 on windows 10.
Could the existing code run on windows 10? 

I tried but so far no success.

**Comment by rahul-tuli** [comment]
Hi @gkomix88, The DeepSparse Engine is validated to work on x86 Intel and AMD CPUs running Linux operating systems. Mac and Windows require running Linux in a Docker or virtual machine.

**Comment by thuangb** [comment]
So is Mac and Window support will be available ? Or it is impossible for deepsparse to work on Mac and Window ?

**Comment by bnellnm** [comment]
Hi @thuangb, other than using Docker, WSL or a VM of some type, we currently have no plans to natively support the engine on Windows or MacOS.
