### ISSUE TITLE
no better speed on yolo quant

### ISSUE THREAD

**Issue by RasoulZamani** [neuralmagic/deepsparse#280]
Hi!
How is it going?

At first ,thanks for your good repo and helping to make better and faster model.
I use your yolo example for getting better speed, and I compare base, pruned and quant models as you said. but all result were aproximatly same . 
there is no vnni warning, and my server is ubuntu 18
my code is:

import os
# models : 
yolov5s_base = "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none"

yolov5s_pruned ="zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96"

yolov5s_pruned_quant = "zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94"

source_img = "img.bmp"

print("\n base inference:\n")
bash_cmd = f"python annotate.py {yolov5s_base} --source {source_img} --image-shape 640 640 "
os.system(bash_cmd)

print("\n pruned inference:\n")
bash_cmd = f"python annotate.py {yolov5s_pruned } --source {source_img} --image-shape 640 640 "
os.system(bash_cmd)

print("\n pruned_quant inference:\n")
bash_cmd = f"python annotate.py {yolov5s_pruned_quant} --source {source_img} --quantized-inputs --image-shape 640 640 "
os.system(bash_cmd)

when I run this code in bash script, I get this results:

 base inference:

2022-03-08 20:28:15 __main__     INFO     Results will be saved to annotation_results/deepsparse-annotations-8
model with stub zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none downloaded to /home/fteam/.cache/sparsezoo/cdaaf2c9-a2f1-45d2-841d-45ce123e7b25/model.onnx
2022-03-08 20:28:17 __main__     INFO     Compiling DeepSparse model for /home/fteam/.cache/sparsezoo/cdaaf2c9-a2f1-45d2-841d-45ce123e7b25/model.onnx
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.10.0 (c2458ea3) (release) (optimized) (system=avx512, binary=avx512)
2022-03-08 20:28:18 __main__     INFO     Inference 0 processed in 128.20696830749512 ms
2022-03-08 20:28:18 __main__     INFO     Results saved to annotation_results/deepsparse-annotations-8

 pruned inference:

2022-03-08 20:28:19 __main__     INFO     Results will be saved to annotation_results/deepsparse-annotations-9
model with stub zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96 downloaded to /home/fteam/.cache/sparsezoo/c13e55cb-dd6c-4492-a079-8986af0b65e6/model.onnx
2022-03-08 20:28:21 __main__     INFO     Compiling DeepSparse model for /home/fteam/.cache/sparsezoo/c13e55cb-dd6c-4492-a079-8986af0b65e6/model.onnx
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.10.0 (c2458ea3) (release) (optimized) (system=avx512, binary=avx512)
2022-03-08 20:28:23 __main__     INFO     Inference 0 processed in 124.91464614868164 ms
2022-03-08 20:28:23 __main__     INFO     Results saved to annotation_results/deepsparse-annotations-9

 pruned_quant inference:

2022-03-08 20:28:24 __main__     INFO     Results will be saved to annotation_results/deepsparse-annotations-10
model with stub zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94 downloaded to /home/fteam/.cache/sparsezoo/aabc828b-c199-4766-95e1-53f2abd0fdd3/model.onnx
2022-03-08 20:28:26 __main__     INFO     Compiling DeepSparse model for /home/fteam/.cache/sparsezoo/aabc828b-c199-4766-95e1-53f2abd0fdd3/model.onnx
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.10.0 (c2458ea3) (release) (optimized) (system=avx512, binary=avx512)
2022-03-08 20:28:28 __main__     INFO     Inference 0 processed in 114.76516723632812 ms
2022-03-08 20:28:28 __main__     INFO     Results saved to annotation_results/deepsparse-annotations-10

as you see quant pruned has no more speed !
pls guide me to get faster result
thanks!

**Comment by mgoin** [comment]
Hi there @RasoulZamani , thanks for opening this issue. 

It looks like you are using our `annotate.py` example which is best used to see the quality of the model result on real images. If you would like to specifically benchmark the performance of inference for different models, we recommend trying our `benchmark.py` example in the same directory. 

Using `annotate.py` as a benchmarking script is not recommended since the time reported for inference includes all of the time for pre-processing, inference, post-processing, annotation, display, and saving in a functional but non-optimized pipeline mostly in pure Python made for ease of use, not for performance. So please try the benchmark script to see what result you get there and we can help you with what you'd like to try next.

Thanks!

**Comment by RasoulZamani** [comment]
thanks for replying me!

yes I was used your annotate.py on base and qunt models (of yolov5 )

I want see effect of various models on one sample (batch size =1)
by annotate.py I see no difference in speed

what is your suggestion?

**Comment by mgoin** [comment]
Right so annotate.py only works with the data you give it and a single image by itself isn't how we usually measure performance. Usually there is a stream of batch size=1 images coming into the engine and you can measure that scenario with `benchmark.py` that I mentioned before. 

You can run something like:
```
python benchmark.py zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96 --image-shape 800 800 --batch-size 1 
```

If you'd like to continue to use annotate.py then I would recommend running multiple images or a video through to see how the performance averages over time.

**Comment by RasoulZamani** [comment]
do you mean that your sparse method  not effect on single inference? we should use it in batch mode to gain better speed?

**Comment by RasoulZamani** [comment]
I found that running model itself speed up, but because of postprocessing after it, maybe we cant see it in end to end program.

**Comment by mgoin** [comment]
> 
> do you mean that your sparse method  not effect on single inference? we should use it in batch mode to gain better speed? 

Our sparse method does have speedup at batch size=1. What I was suggesting is running more than one image, one-after-another not a higher batch size, through the compiled model to evaluate the performance. 

The first few inferences might be slow while the engine is warming up and loading everything into cache, but it will settle on a stable average eventually.
