### ISSUE TITLE
The AVX instruction set is unknown. Set NM_ARCH to one of avx512,avx2 to continue.

### ISSUE THREAD

**Issue by Jason-Hsu** [neuralmagic/deepsparse#292]
Hello, thanks for your work. I got an issue when executing the example. Not sure if I misunderstand anything. 
Sorry that I mislabel it to a bug, but I don't know how to delete this label.

**Describe the bug**
To execute the example - [ultralytics-yolo](https://github.com/neuralmagic/deepsparse/tree/main/examples/ultralytics-yolo), it would have the error as following.
```
The AVX instruction set is unknown. Set NM_ARCH to one of avx512,avx2 to continue.
```

**Expected behavior**
It could successfully have object detection output.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Ubuntu 16.04
2. Python version [e.g. 3.7]: 3.9.10
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]: 0.11.0
4. ML framework version(s) [e.g. torch 1.7.1]: torch 1.9.0
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]: 

	- Onnx: 1.10.1
	- sparseml: 0.11.0
	- numpy: 1.22.3

7. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
```
I can't execute the above command, but got the same error.
My CPU is Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz.

**To Reproduce**
Exact steps to reproduce the behavior:
```
python annotate.py   zoo:cv/detection/yolov5-s/pytorch/ultr
alytics/coco/pruned_quant-aggressive_94  --source /home/dev/Documents/teco/experiment/tflite1/test1.jpg  --image-shape 416 416 --device cpu
# or
python annotate.py -h
```

**Errors**

Traceback (most recent call last):
  File "/home/dev/Documents/teco/experiment/deepsparse/examples/ultralytics-yolo/annotate.py", line 119, in <module>
    from deepsparse import compile_model
  File "/home/dev/mambaforge/envs/tflite1-env/lib/python3.9/site-packages/deepsparse/__init__.py", line 33, in <module>
    from .engine import *
  File "/home/dev/mambaforge/envs/tflite1-env/lib/python3.9/site-packages/deepsparse/engine.py", line 44, in <module>
    from deepsparse.lib import init_deepsparse_lib
  File "/home/dev/mambaforge/envs/tflite1-env/lib/python3.9/site-packages/deepsparse/lib.py", line 27, in <module>
    CORES_PER_SOCKET, AVX_TYPE, VNNI = cpu_details()
  File "/home/dev/mambaforge/envs/tflite1-env/lib/python3.9/site-packages/deepsparse/cpu.py", line 242, in cpu_details
    arch = cpu_architecture()
  File "/home/dev/mambaforge/envs/tflite1-env/lib/python3.9/site-packages/deepsparse/cpu.py", line 184, in cpu_architecture
    raise OSError(
OSError: Neural Magic: The AVX instruction set is unknown. Set NM_ARCH to one of avx512,avx2 to continue.

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by tlrmchlsmth** [comment]
Hi @Jason-Hsu thanks for reporting your issue. Unfortunately we do not support your i7-3770. The DeepSparse Engine requires, at minimum, CPUs that support the AVX2 instruction set, and your processor only supports up to AVX.
