### ISSUE TITLE
YOLOv3 examples link in the root README leads to a 404

### ISSUE THREAD

**Issue by breaks-software** [neuralmagic/deepsparse#365]
The public https://github.com/neuralmagic/deepsparse/tree/main/examples file has the following link to YOLOv3 examples.
https://github.com/neuralmagic/deepsparse/blob/main/examples/ultralytics-yolov3/
This link leads to a GitHub 404 page, indicating that the target directory does not exist.

I expected the link to bring me to a valid page.  Perhaps it should be https://github.com/neuralmagic/deepsparse/tree/main/examples/ultralytics-yolo ?

**Comment by mgoin** [comment]
Hi @breaks-software, nice catch. Yes we updated that `ultralytics-yolo` example to include YOLOv3 and YOLOv5. This `examples/README` needs to be updated in general for the new examples.

**Comment by mgoin** [comment]
@breaks-software just landed a fix for this so closing, thanks again!
