### ISSUE TITLE
Unable to install deepsparse-transformers dependencies

### ISSUE THREAD

**Issue by kristina-licenberger** [neuralmagic/deepsparse#376]
**The bug**
Unable to install deepsparse-transformers dependencies

**Environment**

1. OS release='4.15.0-117-generic', version=118-Ubuntu SMP, machine='x86_64':
2. Python 3.6.12 :
3. DeepSparse version 0.12.1:
4. ML framework version(s) torch-1.10.2:
5. Other Python package versions transformers-4.18.0 :
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture():
{'vendor': 'GenuineIntel', 'isa': 'avx2', 'vnni': False, 'num_sockets': 2, 'available_sockets': 2, 'cores_per_socket': 12, 'available_cores_per_socket': 12, 'threads_per_core': 2, 'available_threads_per_core': 2, 'L1_instruction_cache_size': 32768, 'L1_data_cache_size': 32768, 'L2_cache_size': 262144, 'L3_cache_size': 31457280}

**To Reproduce**
1.pip install deepsparse
2.pip install https://github.com/neuralmagic/transformers/releases/download/nightly/transformers-4.18.0.dev0-py3-none-any.whl

**Errors**
I wanted to try deepsparse.transformers for summarization task but as an output I got error
![image](https://user-images.githubusercontent.com/99014157/169256815-c4740c1b-cf59-4678-8ca7-b94621267dec.png)
 which lead me to the error I am writing you about
![image](https://user-images.githubusercontent.com/99014157/169256954-2416e257-2af0-488a-bfc0-07ce0ab30c58.png)

I tried to find transformers-4.18.0.dev0-py3-none-any.whl following the path but I can not find the folder releases in transformers
https://github.com/neuralmagic/transformers

**Comment by markurtz** [comment]
Hi @kristina-licenberger, we're unable to reproduce using the pip install command linked here. It looks like there may be a local issue with HTTPS/SSL working for the pip setup. Can you verify that the local time for the server is correct and up to date and additionally pip is up to date?

Separately you can download the whl file from here to install from a local file: https://github.com/neuralmagic/transformers/releases/tag/nightly

**Comment by kristina-licenberger** [comment]
Hi @markurtz, I managed to download the whl file from the link you have provided me and install deepsparse-transformers. Thank you :)
