### ISSUE TITLE
ERROR: Failed building wheel for deepsparse  & unable to install deepsparse on windows as well as on macos.

### ISSUE THREAD

**Issue by animeesh** [neuralmagic/deepsparse#396]
**Describe the bug**

**Expected behavior**

**Environment**
Include all relevant environment information:
1. Mac OS 
2. Python version 3.9.7:
3. DeepSparse version latest
4. CPU - m1 chip

**To Reproduce**
Exact steps to reproduce the behavior:
conda created environment 
installed onnx - and pip installed deepsparse 

**Errors**
 error: Native Mac is currently unsupported for the DeepSparse Engine. Please run on a Linux system or within a Linux container on Mac. More info can be found in our docs here: https://docs.neuralmagic.com/deepsparse/source/hardware.html
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for deepsparse
Failed to build deepsparse
ERROR: Could not build wheels for deepsparse, which is required to install pyproject.toml-based projects

**Comment by mgoin** [comment]
Hi @animeesh this error is well-formed as the deepsparse engine doesn't support non-Linux operation systems at the moment. Sorry we can't offer support for these systems at the moment but it is something we're considering in the long-term.

**Comment by animeesh** [comment]
thankyou for reply
