### ISSUE TITLE
Please make an ARM version for Raspberry Pi 4

### ISSUE THREAD

**Issue by bitcoinmeetups** [neuralmagic/deepsparse#401]
Hello,

I'm BM. A very nice and polite guy.

Please make an ARM version for Raspberry Pi 4

**Comment by mgoin** [comment]
Hi @bitcoinmeetups thanks for letting us know about your target hardware. We are actively working on an ARM version of the deepsparse engine! It's still in development and we will hopefully have something to share in the coming months.

**Comment by hcordobest** [comment]
That's great news! Is it there any place we can subscribe to be informed when it's available or become beta tester? Thanks!

**Comment by mgoin** [comment]
@hcordobest we'll make note to reach out early and you can sign up for email announcements [here](https://neuralmagic.com/subscribe/) or join our slack community [here](https://join.slack.com/t/discuss-neuralmagic/shared_invite/zt-q1a1cnvo-YBoICSIw3L1dmQpjBeDurQ).

**Comment by hcordobest** [comment]
Great! Signed up now :+1:

**Comment by mgoin** [comment]
Will keep you both posted when ARM is available, thanks!
