### ISSUE TITLE
getting low fps  & inference issue

### ISSUE THREAD

**Issue by akashAD98** [neuralmagic/deepsparse#415]
1.i used this repo 
https://github.com/neuralmagic/deepsparse/tree/main/examples/ultralytics-yolo
& this command
!python annotate.py \
   zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned_quant-aggressive_94\
    --source "/content/loc1min.mp4" \
    --quantized-inputs \
    --image-shape 416 416 \
    --save-dir '/content/ops/' \
    --model-config '/content/coco128.yaml'\
    --device 'cpu'
  
& im  getting low fps on cpu, (yolov5s model) its normal fps or should we get 50-60 fps? bcz you have mentioned that model will be 10x faster. but its very less.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/62583018/172156490-37539fe1-eba7-41c8-bbe2-88cfc30c8bd1.png">

2. i trained  model usiing sparsml repo on coco128 data for 40 epochs & converted .pth model into onnx & tried same inference script 
!python annotate.py \
    /content/sparseml/integrations/ultralytics-yolov5/yolov5/runs/train/exp2/weights/best.onnx \
    --source "/content/loc1min.mp4" \
    --quantized-inputs \
    --image-shape 416 416 \
    --save-dir '/content/ops/' \
    --model-config '/content/coco128.yaml'
    --device 'cpu'
& getting this issue.
<img width="529" alt="image" src="https://user-images.githubusercontent.com/62583018/172157880-4d79d4ae-a703-453b-9758-aae3e5b3ddf7.png">

What's wrong here? my goal is to use a custom data train model with sparceml & do inference using deepspare.

**Comment by akashAD98** [comment]
CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
GPU: Intel(R) UHD Graphics (iGPU)

!python annotate.py
/content/sparseml/integrations/ultralytics-yolov5/yolov5/runs/train/exp2/weights/best.onnx
--source "/content/loc1min.mp4"
--quantized-inputs
--image-shape 416 416
--save-dir '/content/ops/'
--model-config '/content/coco128.yaml'
--device 'cpu'

this command for inference & yolov5  command for traing 

traing 
!python train.py --data /content/sparseml/integrations/ultralytics-yolov5/yolov5/data/coco128.yaml --cfg ../models_v5.0/yolov5s.yaml --weights zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/pruned-aggressive_96?recipe_type=transfer --hyp data/hyps/hyp.finetune.yaml --recipe ../recipes/yolov5.transfer_learn_pruned.md

conversion to onnx

!python export.py --weights /content/sparseml/integrations/ultralytics-yolov5/yolov5/runs/train/exp2/weights/best.pt  --dynamic

**Comment by KSGulin** [comment]
@akashAD98 the low fps you're seeing may be a result of low computational resources offered by google colab. If you run the same annotation with a baseline model (with the command below), what fps do you see? I would recommend trying a run with the baseline and pruned model back-to-back, as I'm not certain if google colab provided resources vary over time.

```
python annotate.py
zoo:cv/detection/yolov5-s/pytorch/ultralytics/coco/base-none
--source "/content/loc1min.mp4"
--quantized-inputs
--image-shape 416 416
--save-dir '/content/ops/'
--model-config '/content/coco128.yaml'
--device 'cpu'
```

For the model that's giving you an error, could you share the command you used to train it?

**Comment by akashAD98** [comment]
@KSGulin ok ill try this

**Comment by akashAD98** [comment]
@KSGulin  i followed this repo, & I'm able to do training of my custom moel https://github.com/dnth/yolov5-deepsparse-blogpost
