### ISSUE TITLE
Could not build wheels for deepsparse, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by akashAD98** [neuralmagic/deepsparse#418]
im using windows 10 , python 3.7 & creayed new venv for this project,
so window system dosnt have support of deepsparse?
<img width="548" alt="image" src="https://user-images.githubusercontent.com/62583018/172296582-ec37cbdf-9797-4be7-81ce-6c8a02370e70.png">
<img width="662" alt="image" src="https://user-images.githubusercontent.com/62583018/172296629-92fc3c21-f0db-41ae-bef0-4a6708a87603.png">

**Comment by KSGulin** [comment]
Hi @akashAD98, That's correct. The engine currently supports x86 CPUs running on Linux. You can, however, install deepsparse if you're running on a (linux-based) VM or docker from Windows

**Comment by akashAD98** [comment]
@KSGulin got it thanks
