### ISSUE TITLE
Unable to install deepsparse

### ISSUE THREAD

**Issue by manish33scss** [neuralmagic/deepsparse#494]
trying : pip install sparseml[torchvision] deepsparse
got the following error,   

![deep_error](https://user-images.githubusercontent.com/44940688/177292248-50d341ef-6ad0-4384-aa54-12f2c3aa4b55.JPG)

PS:  Used in new env as well, same error , although this command works fine in colab. 
Help me out, what am i missing here ?

**Comment by bfineran** [comment]
hi @manish33scss could you provide information on your operating system and CPU? It looks like you may be on Windows, if that is the case, deepsparse is currently only compiled for Linux and running in a docker container may be a preferred pathway

**Comment by manish33scss** [comment]
Yes i am using windows, and will it work on jetson nano ?

**Comment by bfineran** [comment]
so for windows as mentioned above using a docker container will be the best supported pathway (see https://github.com/neuralmagic/deepsparse/tree/main/docker for an example).

For jetson nano, the CPU is ARM based which deepsparse does not currently support, but this is on the near term roadmap.  SparseML could still be used however to create smaller models for deployment on edge devices such as the jetson.

**Comment by aurelien-m** [comment]
> so for windows as mentioned above using a docker container will be the best supported pathway (see https://github.com/neuralmagic/deepsparse/tree/main/docker for an example).
> 
> For jetson nano, the CPU is ARM based which deepsparse does not currently support, but this is on the near term roadmap. SparseML could still be used however to create smaller models for deployment on edge devices such as the jetson.

Do you have an idea when this could be released? This could be great for embedded devices (BeagleBone AI-64 or Raspberry Pi 4 for example)! Anyways, if there's a way to get updated about this, I'll definitely be interested. Thanks :smile:

**Comment by rsnm2** [comment]
We are actively working on ARM for DeepSparse. We are very close to finishing server-grade ARM devices (AWS Graviton/Ampere for instance) and are then pivoting quickly to focus on embedded devices and are looking for design partners to provide input on the roadmap. Please reachout to me here or at rshaw@neuralmagic.com if interested in discussing further.
