### ISSUE TITLE
Deepsparse model compilation error on YOLOv7

### ISSUE THREAD

**Issue by divy-kala** [neuralmagic/deepsparse#579]
**Bug Description**
I am trying to sparsify and run [YOLOv7](https://github.com/WongKinYiu/yolov7) on Deepsparse. I used SparseML to sparsify the model, and was able to get a sparsity of 0.75. Exporting this sparse YOLOv7 to an onnx model and running it on OpenVino was successful so the model was created fine (albeit with only moderate performance improvements). 
Running the same onnx model on Deepsparse however results in an error while compiling the model: compile_model(onnx_filepath, batch_size)

**Expected behavior**
The onnx model should compile successfully and then run on Deepsparse.

**Environment**

1. OS: Ubuntu 20.04.3 LTS
2. Python version: 3.7.13
3. DeepSparse version or commit hash: 1.0.2
4. ML framework version(s): torch 1.9.0, torchvision 0.10.0
5. Other Python package versions: SparseML 1.0.1, numpy 1.19.5, ONNX 1.10.1
6. CPU info - 
{'L1_data_cache_size': 32768, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 262144, 'L3_cache_size': 36700160, 'architecture': 'x86_64', 'available_cores_per_socket': 12, 'available_num_cores': 24, 'available_num_hw_threads': 24, 'available_num_numa': 2, 'available_num_sockets': 2, 'available_sockets': 2, 'available_threads_per_core': 1, 'cores_per_socket': 12, 'isa': 'avx2', 'num_cores': 24, 'num_hw_threads': 24, 'num_numa': 2, 'num_sockets': 2, 'threads_per_core': 1, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': 'Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz', 'vnni': False}

**To Reproduce**
Exact steps to reproduce the behavior:
```
from deepsparse import compile_model
from deepsparse.utils import generate_random_inputs

onnx_filepath = "pruned_finalized_144_torch.onnx"
batch_size = 1
inputs = generate_random_inputs(onnx_filepath, batch_size)

engine = compile_model(onnx_filepath, batch_size) #<---- error
```

**Errors**
2022-08-16 13:22:33 deepsparse.utils.onnx INFO     Generating input 'images', type = float32, shape = [1, 3, 640, 640]
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 1.0.2 (7dc5fa34) (release) (optimized) (system=avx2, binary=avx2)
[nm_ort 7fe93a051340 >ERROR< supported_subgraphs /home/ubuntu/build/nyann/src/onnxruntime_neuralmagic/supported/subgraphs.cc:858] ==== FAILED TO COMPILE ====
Unexpected exception message: map::at
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 1.0.2 (7dc5fa34) (release) (optimized)
Date: 08-16-2022 @ 13:22:34 UTC
OS: Linux AZJAIVISIONGPUL05 5.11.0-1028-azure #31~20.04.2-Ubuntu SMP Tue Jan 18 08:46:15 UTC 2022
Arch: x86_64
CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
Vendor: GenuineIntel
Cores/sockets/threads: [24, 2, 24]
Available cores/sockets/threads: [24, 2, 24]
L1 cache size data/instruction: 32k/32k
L2 cache size: 0.25Mb
L3 cache size: 35Mb
Total memory: 440.897G
Free memory: 339.802G

Assertion at /home/ubuntu/build/nyann/src/onnxruntime_neuralmagic/nm_execution_provider.cc:76

Backtrace:
 0# wand::detail::abort_prefix(std::ostream&, char const*, char const*, int, bool, bool, unsigned long) in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 1# 0x00007FE85F146492 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 2# 0x00007FE85F147F2C in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 3# 0x00007FE85F410261 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 4# 0x00007FE85FAA40B8 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 5# 0x00007FE85FAA6ACC in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 6# 0x00007FE85FAA9D99 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 7# 0x00007FE85F3F094B in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 8# 0x00007FE85F3F8BCE in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
 9# 0x00007FE85F39F73D in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
10# 0x00007FE85F39F9D5 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libonnxruntime.so.1.10.0
11# deepsparse::ort_engine::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::shared_ptr<wand::parallel::scheduler_factory_t>) in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/libdeepsparse.so
12# 0x00007FE8E9282309 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/deepsparse_engine.so
13# 0x00007FE8E92826DE in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/deepsparse_engine.so
14# 0x00007FE8E92C7D0D in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/deepsparse_engine.so
15# 0x00007FE8E9298A74 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/deepsparse/avx2/deepsparse_engine.so
16# _PyMethodDef_RawFastCallDict in /data3/anaconda3/envs/export_yolov7/bin/python
17# _PyObject_FastCallDict in /data3/anaconda3/envs/export_yolov7/bin/python
18# 0x000055E951FD01C3 in /data3/anaconda3/envs/export_yolov7/bin/python
19# PyObject_Call in /data3/anaconda3/envs/export_yolov7/bin/python
20# 0x000055E951F5EF94 in /data3/anaconda3/envs/export_yolov7/bin/python
21# 0x000055E951FDB847 in /data3/anaconda3/envs/export_yolov7/bin/python
22# 0x00007FE86CCFD907 in /data3/anaconda3/envs/export_yolov7/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-37m-x86_64-linux-gnu.so
23# _PyObject_FastCallKeywords in /data3/anaconda3/envs/export_yolov7/bin/python

Please email a copy of this stack trace and any additional information to: support@neuralmagic.com
Aborted

**Additional context**

Sparse ONNX model on which the error appeared: [link](https://divykala-my.sharepoint.com/:u:/g/personal/divykala_divykala_onmicrosoft_com/ETLRNuEmb95Lrj3GS8Yjr0EBbDWJQC9SmqNMbEKqpp7Mrg?e=aoxT9D)
Sparse pytorch model form which the ONNX model was created: [link](https://divykala-my.sharepoint.com/:u:/g/personal/divykala_divykala_onmicrosoft_com/EbPlC3SvXQJGn0jFvOLKaHgBc-VgOVl3fJH05B7iHAUavQ?e=XX7Yb0)

**Comment by tlrmchlsmth** [comment]
Hi @divy-kala, thanks for your bug report and thanks for providing the onnx file. I'll try to reproduce the issue and see if I can find a solution for you.

**Comment by tlrmchlsmth** [comment]
Hi @divy-kala, we reproduced this issue and have tested that it works in 1.1.0. Please let us know if it works for you. Thanks!
