### ISSUE TITLE
ImportError: cannot import name 'arrays_to_bytes' from 'deepsparse.utils'

### ISSUE THREAD

**Issue by adrianosantospb** [neuralmagic/deepsparse#65]
**Describe the bug**
Trying to run the server-client example.

**Environment**
Include all relevant environment information:
Ubuntu 18.04

2. Python version : 3.8
3. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:

 deepsparse             0.1.1

4. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:

{'vendor': 'GenuineIntel', 'isa': 'avx2', 'vnni': False, 'num_sockets': 1, 'available_sockets': 1, 'cores_per_socket': 8, 'available_cores_per_socket': 8, 'threads_per_core': 1, 'available_threads_per_core': 1, 'L1_instruction_cache_size': 32768, 'L1_data_cache_size': 32768, 'L2_cache_size': 262144, 'L3_cache_size': 12582912}

**To Reproduce**
from deepsparse.utils import arrays_to_bytes, bytes_to_arrays

**Errors**
Traceback (most recent call last):
  File "server.py", line 62, in <module>
    from deepsparse.utils import arrays_to_bytes, bytes_to_arrays
ImportError: cannot import name 'arrays_to_bytes' from 'deepsparse.utils'

**Comment by bfineran** [comment]
Hi @adrianosantospb thank you for reporting this issue.  The `main` branch is currently updated new features that are incompatible with the deepsparse 0.1.0 release that is installed.

To run our latest build, you can install `deepsparse-nightly` which will include the API updates.

```
pip uninstall deepsparse

pip install deepsparse-nightly
```

Verify that the latest nightly was installed with `pip freeze | grep deepsparse`, the version should be `deepsparse-nightly==0.2.0.20210325`

Additionally, our official 0.2.0 version will be released soon that will be compatible with the current API on the `main` branch.

**Comment by adrianosantospb** [comment]
Hi, @bfineran . It works well. Tks!
And tks you all for this great job. So... I'm very excited to test it. I'm training to create a client-server App. I've already converted my model and I'm following the steps from the repo. My idea is to get frames from a video and send them to the server-side, process the detection and return the output to the client to draw the box. (like this https://github.com/adrianosantospb/unifacisa-visao-computacional/tree/master/modulo2/5-publicacao).
But now I'm getting some errors. I'm totally sure I'm doing something wrong and, If it's possible, I'd like your help to do this.

I'm doing something like this on the client-side.

`# Get the current frame and the status
    status, frame = camera.read()

    # Stop condition
    key = cv2.waitKey(1) & 0xFF

    if (status == False or key == ord("q")):
        break

    img = frame.copy()

    _, img_encoded = cv2.imencode('.jpg', img)

    data = arrays_to_bytes(img_encoded)

    # Send image to analyze and getting tags as return
    response = requests.post(test_url, data=data)`


And I'm doing something like this on the server-side.

` @app.route("/api/predict", methods=["POST"])
    def predict():
        data = flask.request.get_data()

        inputs = bytes_to_arrays(data)
        print(f"Received {len(inputs)} inputs from client")

        print("Executing model")
        outputs, elapsed_time = engine.timed_run(inputs)

        print(f"Inference time took {elapsed_time * 1000.0:.4f} milliseconds")
        print(f"Produced {len(outputs)} output tensors")
        return arrays_to_bytes(outputs)`

And I'm getting this output.

`127.0.0.1 - - [25/Mar/2021 16:47:03] "POST /api/predict HTTP/1.1" 500 -
Received 141741 inputs from client
Executing model
[2021-03-25 16:47:05,547] ERROR in app: Exception on /api/predict [POST]
Traceback (most recent call last):
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 82, in predict
    outputs, elapsed_time = engine.timed_run(inputs)
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/deepsparse/engine.py", line 309, in timed_run
    out = self.run(inp, val_inp)
  File "/home/adriano/anaconda3/envs/magic/lib/python3.8/site-packages/deepsparse/engine.py", line 284, in run
    return self._eng_net.execute_list_out(inp)
RuntimeError: NM: error: Expected 1 inputs, received 141741`

**Comment by bfineran** [comment]
The input to `arrays_to_bytes` should be a list of numpy arrays that will be the model input.  Note that the data shape and type should match the model inputs.  The error says `Expected 1 inputs` so the input list should contain exactly one array.  So the image should be loaded as a numpy array (with any preprocessing) and wrapped in a list.

For example, if your model needs float input shape `(3,300,300)` with batch size 1, the input should be a list with a single `numpy.float32` array with shape `(1,3,224,224)`.  

By the way, this is a great use case for DeepSparse! We actually have a blog about our YOLOv3 performance coming out next week, keep an eye out for it.

**Comment by adrianosantospb** [comment]
Hi @bfineran , tks for your support.
For sure I will write a blog about what I'm doing and I will share the NeuroMagic idea. For now, I'm testing the YOLO as well. I'm testing the YOLO V5. 
I use to use the Ultralytics framework. I have a good model trained (YOLO V3), but I used the previous version from Ultralytics. I will try to convert it to ONNX and test it with NeuroMagic. 
So... just to share what I did to work:

`# Padded resize
        img = letterbox(img0,416)
        # Convert
        img = img[:, :, ::-1].transpose(2, 0, 1)  # BGR to RGB, to 3x416x416
        img = np.ascontiguousarray(img)
        img = torch.from_numpy(img).float()
        img /= 255.0  # 0 - 255 to 0.0 - 1.0
        
        if img.ndimension() == 3:
            img = img.unsqueeze(0).numpy()

        print("Executing model")
        outputs, elapsed_time = engine.timed_run([img])`

**Comment by bfineran** [comment]
Thanks for the update @adrianosantospb.  This looks correct for preprocessing!  We actually have an [integration with Ultralytics](https://github.com/neuralmagic/sparseml/tree/main/integrations/ultralytics) for pruning and quantization if you're interested.

As I mentioned above, we'll be releasing pruned and quantized YOLOv3 models, benchmarking results, and a blog shortly so keep an eye out for that!  I'll also update this issue with that information.

**Comment by adrianosantospb** [comment]
> Thanks for the update @adrianosantospb. This looks correct for preprocessing! We actually have an [integration with Ultralytics](https://github.com/neuralmagic/sparseml/tree/main/integrations/ultralytics) for pruning and quantization if you're interested.
> 
> As I mentioned above, we'll be releasing pruned and quantized YOLOv3 models, benchmarking results, and a blog shortly so keep an eye out for that! I'll also update this issue with that information.

For sure! I will test it. But for the previous version, I think I need to create a conversion script. If you have something to share with me, to be free to do :).
When I finished my experiment, I will share it with you as well.

**Comment by bfineran** [comment]
Definitely! SparseML's `ModuleExporter` tool contains an ease of use function for exporting ONNX files.  You could use it to export the YOLOv3 models from the `ultralytics/yolov3` archive branch. Note that execution times will be longer for the archive models because the graphs contain some of the post-processing whereas the v5 repo moves it outside of the ONNX graph.

Here's an example of putting together the v3 archive repo and `ModuleExporter`. It works for me from the v3 archive branch with `sparseml` installed.

```python
# Imports
import models
from sparseml.pytorch.utils import ModuleExporter
import torch

# Create archived v3 model (random weights)
models.ONNX_EXPORT = True
model = models.Darknet("cfg/yolov3-spp.cfg", (640,640))

# Export to ONNX with SparseML
exporter = ModuleExporter(model, "./models")  # creates models directory to save to
exporter.export_onnx(torch.randn(1, 3, 640, 640), name="yolov3-spp.onnx")
```

**Comment by adrianosantospb** [comment]
Hi @bfineran , I did a test with YOLO V3. To be honest, the conversion was very fast. 
I'm using the YOLO V3 SSP and, after the conversion, I'm getting 4.26 FPS. If it is ok for you, I could submit a merge request with the code I did.

**Comment by adrianosantospb** [comment]
Hi, @bfineran. 

Well, I did a test using YOLO V3. Using images with (416, 416), I've got FPS AVG of 5.63. I don't know if I did something wrong, but I was waiting for something around 20~25fps. Do you have some idea? 
I will share what I wrote. Maybe it could be useful for someone too.

**Comment by bfineran** [comment]
Hi @adrianosantospb thank you for sharing your results.  To achieve best results with DeepSparse, the model should be pruned and quantized, using a CPU with VNNI instructions.  The base model is not pruned or quantized, so it will not be able to benefit from these optimizations in DeepSparse.

I see that you're running on an 8 core CPU with AVX2 enabled.  Without VNNI on the CPU speedups from quantization will not be possible, however, the model could still benefit from pruning on this CPU - around 2x improvement depending on the sparsity level.  You can use our [SparseML-Ultralyticsintegration](https://github.com/neuralmagic/sparseml/tree/main/integrations/ultralytics) and our [recipes](https://docs.neuralmagic.com/sparseml/recipes.html) to easily prune and quantize YOLO models. We can also provide help/feedback if you want to go down this route.  There will also be sample sparsified YOLOv3 models through [SparseZoo](https://github.com/neuralmagic/sparsezoo)

If you have flexibility on CPU, our benchmarks on an 8 core CPU with AVX512 and VNNI (available on AWS!) are at 26FPS for pruned quantized YOLOv3 models and 11FPS for pruned only YOLOv3 models with 640x640 input sizes.

Regarding your code: yes, please do put up a pull request!

**Comment by bfineran** [comment]
Hi @adrianosantospb happy to help.  AVX-512 is not needed for optimization - SparseML can fit into your existing training pipelines.  For deployment/inference with DeepSparse, AVX-512 will give a significant speed-up over AVX-2. If VNNI is available then even more so because then quantization becomes viable for speed-up.  Using a reduced image size on 4 or 8 cores we can get to the 20FPS+ range with these instruction sets.  

Pruning can still get you additional speedup on AVX-2 devices.  To start, try using our existing pruned YOLOv3 model from the [SparseZoo](https://github.com/neuralmagic/sparsezoo).  It is exported for 640,640 images, but you could reduce it to 416 or 320 using this function from our benchmarking example: https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics/deepsparse/deepsparse_utils.py#L128

To compile the DeepSparse engine from this example you would do:
```python
from deepsparse import compile_model

IMAGE_SHAPE= (320, 320)
model_path, _ = modify_yolo_onnx_input_shape(
    "zoo:cv/detection/yolo_v3-spp/pytorch/ultralytics/coco/pruned-aggressive_97",
    IMAGE_SHAPE,
)
model = compile_model(model_path)
```

Additionally, our [YOLOv3 blog](https://hubs.ly/H0KmpyT0) was just released - check it out if you have time, would love to hear your thoughts!

**Comment by adrianosantospb** [comment]
Hi, @bfineran. Tks for spending time with my questions. 

Just to conclude my preliminary analysis.

a) Using the sparseml, we can train our own model with sparse operation (pruning and quantization) parameters set. We need to define the recipe. Yaml to do it. But if we want to get the high Neural Magic performance, we need to run it on a machine with AVX-512 and VNNI. So, if I do this, I will get the final model "sparsed" and the next step is to convert it to an ONNX format to be used in the inference module.

b) I've seen that we can get 20fps with YOLOV3 on the inference module. But do we need to have AVX-512 and VNNI on the deployed device as we need to train a model to get this speed?

**Comment by bfineran** [comment]
Hi @adrianosantospb 

a) yes - training is done to create a model with pruning and quantization using SparseML + recipes.  To get performance during inference, we need to export to ONNX and run with `deepsparse`.  To get the full speedup, the CPU should support AVX-512 and VNNI.
b) We can get 20fps at 640,640 image sizes and up to 50fps at 320,320.  This is with a pruned-quantized model with AVX-512 and VNNI.  These requirements are only for the device used to perform inference.  Training device does not matter as long as we produce our pruned-quantized model with SparseML.
