### ISSUE TITLE
Support for Windows 10

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [neuralmagic/deepsparse#657]
**Is your feature request related to a problem? Please describe.**
Usage under windows 10.

**Describe the solution you'd like**
Support for Windows 10.

**Comment by mgoin** [comment]
Hi @ErfolgreichCharismatisch while we don't support native Windows usage, you can run deepsparse in [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install) or a Linux virtual machine.
