### ISSUE TITLE
Illegal instruction(core dumped)

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [neuralmagic/deepsparse#675]
**Describe the bug**
Illegal instruction(core dumped) when running the sample code.

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Ubuntu 18.04 via WSL on Windows 10
2. Python version [e.g. 3.7]: Python 3.6.9 (default, Jun 29 2022, 11:45:57)
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]: 1.1.0
5. Other Python package versions ONNX: ONNX 1.11.0, sparsezoo 1.1.0
6. CPU info - output of deepsparse/src/deepsparse/arch.bin: Illegal instruction(core dumped)

**To Reproduce**
```
from deepsparse import Pipeline

# SparseZoo model stub or path to ONNX file
model_path = "zoo:nlp/question_answering/bert-base/pytorch/huggingface/squad/12layer_pruned80_quant-none-vnni"
qa_pipeline = Pipeline.create(
    task="question-answering",
    model_path=model_path,
)

my_name = qa_pipeline(question="What's my name?", context="My name is ErfolgreichCharismatisch")
print(my_name)
```

**Errors**
It is recommended to supply json architecture topology file
by setting environment variable NM_ARCH_FILE to the file's location.
If it has already been set, then please verify its contents.
Illegal instruction(core dumped)

**Comment by tlrmchlsmth** [comment]
Hi @ErfolgreichCharismatisch , thanks for the bug report. Could you share the output of `lscpu` so I can see what CPU you're running on?

**Comment by ErfolgreichCharismatisch** [comment]
@tlrmchlsmth Sure

``
Architektur:                   x86_64
CPU Operationsmodus:           32-bit, 64-bit
Byte-Reihenfolge:              Little Endian
CPU(s):                        8
Liste der Online-CPU(s):       0-7
Thread(s) pro Kern:            2
Kern(e) pro Socket:            4
Sockel:                        1
Anbieterkennung:               GenuineIntel
Prozessorfamilie:              6
Modell:                        42
Modellname:                    Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
Stepping:                      7
CPU MHz:                       3401.000
Maximale Taktfrequenz der CPU: 3401,0000
BogoMIPS:                      6802.00
Hypervisor-Anbieter:           Windows Subsystem for Linux
Virtualisierungstyp:           Container
Markierungen:                  fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm pni pclmulqdq est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes xsave osxsave avx hypervisor lahf_lm ibrs ibpb stibp ssbd
``

**Comment by ErfolgreichCharismatisch** [comment]
@ErfolgreichCharismatisch Can you make it work for everyone using the same cpu?
