### ISSUE TITLE
Deploying DeepSparse with Amazon SageMaker

### ISSUE THREAD

**Issue by vinayak-shanawad** [neuralmagic/deepsparse#705]
Hi Team,

We have decided to explore Deepsparse server on SageMaker, went through this [example](https://github.com/neuralmagic/deepsparse/tree/main/examples/aws-sagemaker) and looks great.

How can we introduce custom inference script which includes pre-processing, model inference and post-processing steps?

Thanks in advance.

**Comment by corey-nm** [comment]
@vinayak-shanawad Thanks for raising this issue! Can you describe your use case a bit more? What kind of task are you doing with your model, and what kind of pre/post processing are you using?

Hopefully one of our pre-built Pipelines covers your use case. You can find examples of most of them under the [examples/](https://github.com/neuralmagic/deepsparse/tree/main/examples) folder, but a high level list is:
- image classification (like resnet)
- object detection (like yolo)
- image segmentation (like yolact)
- many language tasks (like question answering, text classification, etc)

If your use case doesn't fit into the pre-built Pipelines, we can work with you to create a custom Pipeline class that runs your pre and post processing, and then serve that using `deepsparse.server` as the sagemaker example does.

**Comment by vinayak-shanawad** [comment]
@corey-nm Thanks for your reply.

We are looking at language tasks (text classification, question answering) where we have to preprocess the text (remove stop word, hyperlinks etc), get the inference from model and post-process the inference results then construct the response as per the client requirements.

We can achieve above requirements in SM Pytorch container by creating custom inference script which includes pre-processing, inference and post-processing.

Hence we are interested to know if we can come up with our own custom inference script then define that as entry point in Deepsparse docker file, build the container and deploy it using SM scripts.

**Comment by vinayak-shanawad** [comment]
@corey-nm

Good day!!

How can we address our use case? Thanks

**Comment by corey-nm** [comment]
@vinayak-shanawad yes we have support for customizing pipelines, I have a [draft PR up](https://github.com/neuralmagic/deepsparse/pull/708/files) for adding an example of how to do this.

The gist of it is, you can subclass the relevant pipeline class and override the pre/post-processing methods. Here's how that might look:

```python
from deepsparse import Pipeline
from deepsparse.transformers.pipelines.question_answering import (
    QuestionAnsweringInput,
    QuestionAnsweringOutput,
    QuestionAnsweringPipeline,
)


TASK = "custom_qa_task"


@Pipeline.register(TASK)
class MyCustomQaPipeline(QuestionAnsweringPipeline):
    def parse_inputs(self, *args, **kwargs) -> QuestionAnsweringInput:
        qa_input: QuestionAnsweringInput = super().parse_inputs(*args, **kwargs)
        # do whatever you want here
        return qa_input

    def process_engine_outputs(self, *args, **kwargs) -> QuestionAnsweringOutput:
        qa_output: QuestionAnsweringOutput = super().process_engine_outputs(
            *args, **kwargs
        )
        # do whatever you want here
        return qa_output
```

Then you can use the dynamic import feature of the deepsparse server to import your custom task/pipeline at run time:

```yaml
endpoints:
    - task: "import:custom_qa_pipeline"
      ...
```

**Comment by vinayak-shanawad** [comment]
@corey-nm Thanks for the details.

I think we have to place "custom_qa_pipeline.py" file in correct server location (Add a COPY line in Dockerfile for "custom_qa_pipeline.py" ) otherwise I'm getting an error when I placed it in directory contains Dockerfile and config.yaml files.

`Traceback (most recent call last):
  File "/venv/bin/deepsparse.server", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/venv/lib/python3.8/site-packages/deepsparse/server/cli.py", line 106, in config
    start_server(
  File "/venv/lib/python3.8/site-packages/deepsparse/server/server.py", line 77, in start_server
    app = _build_app(server_config)
  File "/venv/lib/python3.8/site-packages/deepsparse/server/server.py", line 165, in _build_app
    _add_endpoint(
  File "/venv/lib/python3.8/site-packages/deepsparse/server/server.py", line 217, in _add_endpoint
    pipeline = Pipeline.from_config(pipeline_config, context)
  File "/venv/lib/python3.8/site-packages/deepsparse/pipeline.py", line 530, in from_config
    return cls.create(
  File "/venv/lib/python3.8/site-packages/deepsparse/pipeline.py", line 402, in create
    pipeline_constructor = Pipeline._get_task_constructor(task)
  File "/venv/lib/python3.8/site-packages/deepsparse/pipeline.py", line 341, in _get_task_constructor
    task = dynamic_import_task(module_or_path=task.replace("import:", ""))
  File "/venv/lib/python3.8/site-packages/deepsparse/tasks.py", line 249, in dynamic_import_task
    raise FileNotFoundError(
FileNotFoundError: Unable to find file for custom_qa_pipeline. Looked for custom_qa_pipeline.py under .`

**Comment by corey-nm** [comment]
Yeah the paths will have to consider the working directory of how the docker run command is executed. I think these options should all work:

1. `COPY custom_qa_pipeline.py /custom_qa_pipeline.py` with `task: "import:/custom_qa_pipeline.py"`
2. `COPY custom_qa_pipeline.py /root/custom_qa_pipeline.py` with `task: "import:/root/custom_qa_pipeline.py"`

**Comment by vinayak-shanawad** [comment]
Error details:

`INFO:     127.0.0.1:59060 - "POST /invocations HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/venv/lib/python3.8/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/venv/lib/python3.8/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/venv/lib/python3.8/site-packages/deepsparse/server/server.py", line 242, in _predict
    ) = pipeline.run_with_monitoring(request)
  File "/venv/lib/python3.8/site-packages/deepsparse/pipeline.py", line 256, in run_with_monitoring
    ) = self.__call__(*args, monitoring=True, **kwargs)
  File "/venv/lib/python3.8/site-packages/deepsparse/pipeline.py", line 221, in __call__
    raise ValueError(
ValueError: Outputs of <class 'custom_qa_pipeline.MyCustomQaPipeline'> must be instances of <class 'deepsparse.transformers.pipelines.question_answering.QuestionAnsweringOutput'> found output of type <class 'NoneType'>`

**Comment by corey-nm** [comment]
@vinayak-shanawad thanks I will look into this and get back to you

**Comment by corey-nm** [comment]
@vinayak-shanawad yeah this is definitely related to the sequence length. Our current token classification pipeline requires the tokenizes to be padded to max length:
```python
            truncation=TruncationStrategy.LONGEST_FIRST.value,
            padding=PaddingStrategy.MAX_LENGTH.value,
```

src: https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/transformers/pipelines/token_classification.py#L261

If you make those changes does it work? Does your use case require non-max length padding?

**Comment by vinayak-shanawad** [comment]
@corey-nm Yes, I did try overwriting the default padding and truncation strategy but I was getting above error.

`RuntimeError: NM: error: Got invalid dimensions for input: input_ids for the following indices index: 1 Got: 30 Expected: 128 Please fix either the inputs or the model.`

Yes, we require non-max length padding hence I was trying to overwrite the default tokenizer config in token_classification.py script.

**Comment by corey-nm** [comment]
@vinayak-shanawad Can you speak more about non-max length padding? The deepsparse engine uses the max sequence length at model compilation time to optimize speed, and so it requires all inputs to be padded to that length. Our current pipelines handle padding to max length & then ignores all the outputs for padded inputs. Will that approach work for your use case?

**Comment by vinayak-shanawad** [comment]
@corey-nm
Let's say we have three sequences in a single inference request with different sequence lengths 30, 60, 120 then we will pad the first two sequences 120 which is max length sequence. But I observed that deepsparse engine will pad all three sequences to PaddingStrategy.MAX_LENGTH.value=128 so is it possible set custom max sequence length?

**Comment by corey-nm** [comment]
@vinayak-shanawad we support this through our bucketing feature, where inputs of different length are sent to different "buckets" (basically just another compiled model). e.g. if you configured 3 buckets of size 32, 64, 128, deepsparse would compile 3 separate models with difference sequence lengths, and each input would be sent to the smallest bucket it would fit in. In this case the 30 sequence length would be padded to 32, the 60 would be padded to 64, and 120 to 128.

You can configured this by passing a list into `sequence_length` parameter:
```python
pipeline = Pipeline.create("text_classification", sequence_length=[32, 64, 128])
```
which will auto set up the buckets for you.

**Comment by vinayak-shanawad** [comment]
Thanks @corey-nm But how can we pass the list of `sequence_length` parameter in a custom pipeline?

**Comment by corey-nm** [comment]
@vinayak-shanawad yeah there are a number of ways:
1. if you are using deepsparse.server with a config file, you can set this up with bucketing config as shown here https://github.com/neuralmagic/deepsparse/blob/main/examples/aws-sagemaker/config.yaml#L10
2. If you are instantiating the pipeline object directly, you can pass `sequence_length=[32, 64, 128]` to the create() function or constructor
3. If you want to do this in your custom subclass, you could override `def __init__(...)` to pass in sequence_length to the superclass constructor:
```python
def __init__(self, *args, **kwargs):
    super().__init__(*args, sequence_length=[32, 64, 128], **kwargs)
```

However option 3 will crash if you also try to provide sequence_length in the kwargs from another source (like config)

**Comment by markurtz** [comment]
Hi @vinayak-shanawad, for the custom models we are currently working on an API that will allow you to apply our sparsification technologies to ONNX models without retraining. We hope to have this in an alpha-testing state within the next 2 months. 

Until that is available and if the dense performance gains from DeepSparse are not enough, then our current pathway is applying before the ONNX export. If you have access to your original training weights and training code, you can try out our custom integration pathway or plug it into the current SparseML pathways and use a pre-configured recipe from the SparseZoo. More info is available on our new docs site for those: https://docs.neuralmagic.com/get-started/sparsify-a-model

**Comment by vinayak-shanawad** [comment]
Thanks @markurtz for the confirmation and that will be a very useful feature.

@corey-nm FYI: I handled the above observations in a custom pipeline, what's your thoughts on those observations?

**Comment by corey-nm** [comment]
@vinayak-shanawad By default yes we just return the classification for all words in the sentence. You can use `ignore_labels=["0"]` kwargs when creating the pipeline to not include non-entities https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/transformers/pipelines/token_classification.py#L171.

The prefixes `B-`, `I-` are from the underlying datasets. For example you can see this on the token classification page from huggingface:
```python
label_list = wnut["train"].features[f"ner_tags"].feature.names
label_list
[
    "O",
    "B-corporation",
    "I-corporation",
    "B-creative-work",
    "I-creative-work",
    "B-group",
    "I-group",
    "B-location",
    "I-location",
    "B-person",
    "I-person",
    "B-product",
    "I-product",
]
```
https://huggingface.co/docs/transformers/tasks/token_classification 

> The ner_tag describes an entity, such as a corporation, location, or person. The letter that prefixes each ner_tag indicates > the token position of the entity:
> B- indicates the beginning of an entity.
> I- indicates a token is contained inside the same entity (e.g., the State token is a part of an entity like Empire State Building).
> 0 indicates the token doesn’t correspond to any entity.

**Comment by vinayak-shanawad** [comment]
Awesome, thanks @corey-nm

**Comment by vinayak-shanawad** [comment]
Hi @corey-nm 

I suspect there is a bug in `token_classification.py` default pipeline because it's not filtering default known class label = ["O"] from prediction results.

My config.yaml:

`num_cores: 1
num_workers: 1
integration: sagemaker
endpoints:
    - task: token_classification
      route: /invocations
      model: /opt/ml/model
      batch_size: 1
      ignore_labels: ["O"]`
      
 Snippet from `token_classification.py` default pipeline says default known class label = ["0"] which is zero instead of ["O"]

https://github.com/neuralmagic/deepsparse/blob/1ded99ff9556d0cb983c51206f042536039a4acd/src/deepsparse/transformers/pipelines/token_classification.py#L171

Please have a look. Thanks

**Comment by corey-nm** [comment]
@vinayak-shanawad thanks yes that does seem like a bug, I'll add that to our issue tracking.

For the yaml, you'll need to add ignore_labels under a kwargs key:
```yaml
num_cores: 1
num_workers: 1
integration: sagemaker
endpoints:
  - task: token_classification
    route: /invocations
    model: /opt/ml/model
    batch_size: 1
    kwargs:
      ignore_labels: ["O"]
```
Let me know if that fixes it

**Comment by corey-nm** [comment]
@vinayak-shanawad also FYI I just merged the fix into main in #742, the fix won't be in pypi until next release (1.3)

**Comment by vinayak-shanawad** [comment]
Thanks @corey-nm 

If I use `deepsparse-nightly[server]` then I'm geting below error.
https://github.com/neuralmagic/deepsparse/blob/430161e8db94e0898ed1dc53638319a0039bcfff/examples/aws-sagemaker/Dockerfile#L22

`ValueError: Unable to install and import deepsparse-transformers dependencies check that transformers is installed, if not, install via `pip install https://github.com/neuralmagic/transformers/releases/download/nightly/transformers-4.18.0.dev0-py3-none-any.whl``

So I switched to `switch to deepsparse[server] >= 0.12` but looks like it installs `deepsparse-1.2.0` version then I'm getting below error.

```
Successfully installed aiohttp-3.8.3 aiosignal-1.2.0 async-timeout-4.0.2 attrs-22.1.0 datasets-1.18.4 dill-0.3.6 filelock-3.8.0 frozenlist-1.3.1 fsspec-2022.10.0 huggingface-hub-0.10.1 joblib-1.2.0 multidict-6.0.2 multiprocess-0.70.14 packaging-21.3 pandas-1.5.1 pyarrow-10.0.0 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.6 regex-2022.10.31 responses-0.18.0 sacremoses-0.0.53 scikit-learn-1.1.3 scipy-1.9.3 seqeval-1.2.2 sklearn-0.0 threadpoolctl-3.1.0 tokenizers-0.13.1 transformers-4.18.0.dev0 xxhash-3.1.0 yarl-1.8.1
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2022-11-03 05:34:54 deepsparse.transformers INFO     deepsparse-transformers and dependencies successfully installed
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 1.2.0 COMMUNITY EDITION | (45d54d49) (release) (optimized) (system=avx512, binary=avx512)
/opt/server/serve: line 2:     8 Killed                  deepsparse.server config --port 8080 /root/server-config.yaml
```

**Comment by corey-nm** [comment]
@vinayak-shanawad which is the error in the last snippet? is the killed message not from you cancelling the process?

**Comment by vinayak-shanawad** [comment]
@corey-nm Yes, I did not kill that process and it's from server itself.

**Comment by corey-nm** [comment]
@vinayak-shanawad usually if your process gets killed its using too much memory. Can you tell if that's the case? What kind of instance are you using to run?

**Comment by vinayak-shanawad** [comment]
@corey-nm I did resolve it by restarting the instance to free up the memory. Thank you.

I tried the Deepsparse bucketing feature in following ways and please find the error details below.

1. Pass different sequence_length in bucketing.
```endpoints:
    - task: token_classification
      route: /invocations
      model: /opt/ml/model
      batch_size: 1
      bucketing:
        sequence_lengths: [32, 64, 128]
      kwargs:
          ignore_labels: ["O"]```
          
2. Pass different sequence_length in kwargs.
```endpoints:
    - task: token_classification
      route: /invocations
      model: /opt/ml/model
      batch_size: 1
      kwargs:
          ignore_labels: ["O"]
          sequence_length: [128, 128]```

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/venv/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/venv/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/venv/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/venv/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/venv/lib/python3.8/site-packages/deepsparse/server/server.py", line 220, in _predict
    ) = pipeline.run_with_monitoring(request)
  File "/venv/lib/python3.8/site-packages/deepsparse/pipeline.py", line 818, in __getattr__
    raise AttributeError(
AttributeError: run_with_monitoring not found in BucketingPipeline, and is not a property of TokenClassificationPipeline`

**Comment by corey-nm** [comment]
@vinayak-shanawad thanks looking into this bug

**Comment by vinayak-shanawad** [comment]
Hi @corey-nm, 

We have designed our current NER API in following way.

The API payload contains a list of one or more texts  Each text can be of arbitrary length ranging from sentences to full articles. If the text is too long, the preprocessor (we use Spacy engine) internally splits it into sentences. The NER model is then applied to each sentence in for loop, and the identified entities are mapped back to the raw text. It is recommended that the text is not too long, to avoid API timeout issues. The API payload looks as follows:

`{
    "data": [
        {
            "id": "geuhpvq07vv7jrwk", 
            "text": "George Washington was the first president of the United States of America."
        }
    ]
}`

Example: Let's say we have a following article with multiple sentences, then we use the preprocessor (Spacy engine) to split it into sentences then we predict entities for each sentence in for loop and map it back to raw text.

How can we achieve this using DeepSparse?

`Once a formal government is put in place, the Taliban are expected to face great difficulty in both drawing up economic policy and implementing it.\n\nThis reflects both the organisation's lack of recent experience in running a state and the decision of Western countries to suspend their development aid to Afghanistan.\n\nThis jeopardises the US$3.3bn a year in aid that was pledged at a conference in November 2020.\n\nThe 2021 budget, as originally drawn up, provided for grant aid inflows to make up 50.3% of revenue, with an IMF loan partly funding the fiscal deficit.\n\nThe IMF has stated that Afghanistan will not be able to receive any funds at this point under the extended credit facility that was in place, and that a US$440m allocation in special drawing rights (part of a US$650bn global programme to support post-pandemic recovery in low- income countries) would also not be available.\n\nA large proportion of Afghan- istan's international reserves, put at US$9.4bn in April, is held abroad and will not be available to the incoming government.\n\nAt the same time, leading money transfer companies such as Western Union have suspended their services in Afghanistan (at least temporarily), in the light of sanctions against the Taliban, hitting likely remittance income.\n\nMany charities and non-governmental organisations have also suspended their programmes in Afghanistan.\n\nOver the long term, Western countries are likely to offer humanitarian aid, but only as long as it can be funnelled through aid charities and not through the Taliban government.\n\nIn mid-August, immediately before the Taliban's capture of Kabul, the UN Office for the Co-ordination of Humanitarian Affairs stated that the majority of the Afghan population were \"acutely food-insecure\".\n\nThe decline of the currency following the takeover and the suspension of currency inflows are expected to push up food prices, exacerbating the problem.\n\nThe cessation of domestic conflict, if maintained, will boost agricultural output, but the government may have to resort to encouraging poppy production in order to earn hard currency from opium exports.\n\nIn addition, the country has barely begun to address the coronavirus pandemic.\n\nAround 1.8m vaccine doses had been administered by mid-August, but less than 1% of the population has been fully inoculated.\n\nFull vaccination is a very distant prospect in Afghanistan, well beyond the end of our forecast period.\n\n`

**Comment by vinayak-shanawad** [comment]
@corey-nm What are your thoughts on the above design and is there any way we can achieve that using DeepSparse?

**Comment by rsnm2** [comment]
@vinayak-shanawad

How long are your sequence lengths? Unless they are very very long, you probably should not be storing them in a database.

You have two options:
- Set the `sequence_length` of the pipeline to be as long as possible (for BERT - 512). Then, on the client side, if you have a sequence of length 1000, split it in half (or perhaps submit overlapping chunks) and submit them in a batch or make multiple concurrent requests with batch size 1. (Make sure you set `num_workers` in the server to configure handling multiple requests)

- Alternatively, you could try to write a custom pipeline that splits request on the server side. You can use the `[CustomTaskPipleine (https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/pipelines/custom_pipeline.py)` class to do this. The QA Pipeline actually has this functionality off the shelf if you want some inspiration for how to implement the splitting (https://github.com/neuralmagic/deepsparse/blob/main/src/deepsparse/transformers/pipelines/question_answering.py). This path will require more work as you will have to re-implement the functionality in the `Transformers` and `TokenClassification` Pipelines from scratch, but will keep your client side code cleaner

**Comment by vinayak-shanawad** [comment]
Hi @rsnm2 

Yes, we have sequence lengths with more than 1000 tokens. 

Would it be possible to implement this functionality in the default `TokenClassificationPipeline` like how we have it in `QuestionAnsweringPipeline`? If not, we will handle it in client side.

Thanks

**Comment by bfineran** [comment]
Hi @vinayak-shanawad sequence striding is a feature we have on our backlog for our token classification pipeline but have not gotten around to.  Were you able to get it working from the client side?

**Comment by mgoin** [comment]
Hi @vinayak-shanawad we wrote an example of striding for token classification in this Huggingface Space: https://huggingface.co/spaces/neuralmagic/ner-long-text
Hope it is helpful!
