### ISSUE TITLE
Question Answering Pipeline slower than the benchmark

### ISSUE THREAD

**Issue by TejaGollapudi** [neuralmagic/deepsparse#724]
Hi,  I'm currently testing out the Question answering pipeline.

I'm using the code of below format to benchmark the QA pipeline
```
import deepsparse
from deepsparse.engine import Context


model_path = 'zoo:nlp/question_answering/distilbert-none/pytorch/huggingface/squad/pruned80_quant-none-vnni '
context = Context(num_cores=8)
qaModelpipeline = deepsparse.Pipeline.create(task="question-answering", model_path=model_path, sequence_length = 384 , context=context)

times =[]
for question_q, context_c in q_pairs: # about 200 items
    st = time.time()
    and = qaModelpipeline(question=question_q, context=context_c)
    et = time.time()
    times.append(et-st)

```
I get the compute times in seconds (s) as : 
|MODEL_NAME |  25th percentile | 75th Percentile | 95th Percentile | 99th Percentile  | Median    |    Mean    |    Max     |   Min     |
|----------|-----------------|-----------------|-----------------|------------------|-----------|------------|------------|------------|
| zoo:nlp/question_answering/distilbert-none/pytorch/huggingface/squad/pruned80_quant-none-vnni | 0.0915 | 0.1833 | 0.1894 | 0.2097 | 0.1796 | 0.1499 | 0.2875 | 0.0883|

Whereas when I run the deepsparse benchmark, I see a 10x improvement in the performance:
```
{
  "engine": "deepsparse.engine.Engine:\n\tonnx_file_path: /home/jovyan/.cache/sparsezoo/629c69c8-e645-4783-9575-dd1b34b078bd/model.onnx\n\tbatch_size: 1\n\tnum_cores: 8\n\tnum_streams: 1\n\tscheduler: Scheduler.multi_stream\n\tcpu_avx_type: avx512\n\tcpu_vnni: True",
  "version": "1.1.0",
  "orig_model_path": "zoo:nlp/question_answering/distilbert-none/pytorch/huggingface/squad/pruned80_quant-none-vnni",
  "model_path": "/home/jovyan/.cache/sparsezoo/629c69c8-e645-4783-9575-dd1b34b078bd/model.onnx",
  "batch_size": 1,
  "input_shapes": null,
  "num_cores": 8,
  "scenario": "multistream",
  "scheduler": "Scheduler.multi_stream",
  "seconds_to_run": 10,
  "num_streams": 1,
  "benchmark_result": {
    "scenario": "multistream",
    "items_per_sec": 70.76579563677444,
    "seconds_ran": 10.004833459854126,
    "iterations": 708,
    "median": 13.620257377624512,
    "mean": 14.107972215124443,
    "std": 1.1918606229115842,
    "25.0%": 13.471245765686035,
    "50.0%": 13.620257377624512,
    "75.0%": 14.026463031768799,
    "90.0%": 16.805315017700195,
    "95.0%": 16.99918508529663,
    "99.0%": 17.50486612319946,
    "99.9%": 20.98847818374654
  }
```

Am I missing something when I am using the QA pipeline causing this performance difference? 

Hardware information: 
```
deepsparse.check_hardware
GenuineIntel CPU detected with 32 cores. (32 sockets with 1 cores each)
DeepSparse FP32 model performance supported: True.
DeepSparse INT8 (quantized) model performance supported: TRUE.

Additional CPU info: {'L1_data_cache_size': 32768, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 1048576, 'L3_cache_size': 37486592, 'architecture': 'x86_64', 'available_cores_per_socket': 1, 'available_num_cores': 32, 'available_num_hw_threads': 32, 'available_num_numa': 32, 'available_num_sockets': 32, 'available_sockets': 32, 'available_threads_per_core': 1, 'cores_per_socket': 1, 'isa': 'avx512', 'num_cores': 32, 'num_hw_threads': 32, 'num_numa': 32, 'num_sockets': 32, 'threads_per_core': 1, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': 'Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz', 'vnni': True}
```
Thank you

**Comment by corey-nm** [comment]
Thanks for reaching out! Two things I notice:
1. deepsparse.benchmark is operating directly on pre-tokenized data (engine inputs), whereas Pipeline has to also tokenize inputs and some other pre/post processing.
2. I believe the default sequence length is 128. So deepsparse.benchmark is operating on sequence length 128 items, and you explicitly set the pipeline to use sequence length 384. This will have a non-negligible impact because transformers efficiency depends on sequence length

**Comment by tlrmchlsmth** [comment]
Hi @TejaGollapudi, thanks for sharing your issue.

There are some strange things in your `deepsparse.check_hardware` output that are confusing to us. First that the engine thinks that your system has 32 cores, whereas your processor only has 26 (see [here](https://www.intel.com/content/www/us/en/products/sku/199346/intel-xeon-gold-6230r-processor-35-75m-cache-2-10-ghz/specifications.html)) and second that the engine thinks that your system has 32 sockets, each with a single core.

Something is going wrong here :grin:. Could you share some more information about your environment? E.g. are you running in a virtualized environment, what cloud provider if any are you running on, etc?

**Comment by TejaGollapudi** [comment]
Thank you for the quick reply 😃. 

@corey-nm  
1. I've benchmarked HuggingFace Pipeline with the 'deepset/minilm-uncased-squad2' model for the same sequence length. I get a Median response time of 0.102 s.  The preprocessing and post-processing steps don't feel like an overhead here for a normal PyTorch model ( I didn't benchmark the individual steps 😅) .  Are there any differences between the HuggingFace QA pipeline and the Deepsprase QA pipeline which may cause pre-processing and post-processing to be slower?
2. 
```
2022-10-26 21:49:04 deepsparse.benchmark.benchmark_model INFO     Thread pinning to cores enabled
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 1.1.0 COMMUNITY EDITION (a436ca67) (release) (optimized) (system=avx512_vnni, binary=avx512)
2022-10-26 21:49:10 deepsparse.benchmark.benchmark_model INFO     deepsparse.engine.Engine:
        onnx_file_path: /home/jovyan/.cache/sparsezoo/629c69c8-e645-4783-9575-dd1b34b078bd/model.onnx
        batch_size: 1
        num_cores: 8
        num_streams: 1
        scheduler: Scheduler.multi_stream
        cpu_avx_type: avx512
        cpu_vnni: True
INFO:deepsparse.benchmark.benchmark_model:deepsparse.engine.Engine:
        onnx_file_path: /home/jovyan/.cache/sparsezoo/629c69c8-e645-4783-9575-dd1b34b078bd/model.onnx
        batch_size: 1
        num_cores: 8
        num_streams: 1
        scheduler: Scheduler.multi_stream
        cpu_avx_type: avx512
        cpu_vnni: True
2022-10-26 21:49:10 deepsparse.utils.onnx INFO     Generating input 'input_ids', type = int64, shape = [1, 384]
INFO:deepsparse.utils.onnx:Generating input 'input_ids', type = int64, shape = [1, 384]
2022-10-26 21:49:10 deepsparse.utils.onnx INFO     Generating input 'attention_mask', type = int64, shape = [1, 384]
INFO:deepsparse.utils.onnx:Generating input 'attention_mask', type = int64, shape = [1, 384]
2022-10-26 21:49:10 deepsparse.benchmark.benchmark_model INFO     Starting 'multistream' performance measurements for 10 seconds
```
While generating the inputs it's generating in the shape of [1,384] so I was under the assumption that it was functioning with an MSL of 384.
<hr>
@tlrmchlsmth I just noticed it, thanks for pointing it out. I'll have a look at it and will get back to you on it.
