### ISSUE TITLE
Diffusion using sparse

### ISSUE THREAD

**Issue by TheProtaganist** [neuralmagic/deepsparse#777]
Hi I am trying to run Glide text to image model on huggingface but I don't know how yet. Also does this work with stable diffusion?

**Comment by mgoin** [comment]
Hi @TheProtaganist we haven't had the chance to run text-to-image models yet. Have you been able to export them to ONNX? It would be fair to try I think.

**Comment by ClashSAN** [comment]
@mgoin @TheProtaganist https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/onnx I have 7-8 other finetuned onnx models I've successfully run through the script. I'm extremely interested in testing this, and would like some guidance..I don't code, but I've used other people's scripts to convert to onnx int8 for <1.4gb ram peak inference with a 256x256 fine-tuned model, also have used an openvino optimized fork, and I'm wondering what the performance will be.

**Comment by mgoin** [comment]
@ClashSAN can you share some code for the ONNX pipeline for these models? I think this is something we can work on to get running!

**Comment by mgoin** [comment]
Feel free to reopen if you have something to try!

**Comment by ClashSAN** [comment]
hi @mgoin, sorry for not checking in, my pings are turned off.

```
from diffusers import StableDiffusionOnnxPipeline
import torch
from diffusers import (
    DDPMScheduler,
    DDIMScheduler,
    PNDMScheduler,
    LMSDiscreteScheduler,
    EulerDiscreteScheduler,
    EulerAncestralDiscreteScheduler,
    DPMSolverMultistepScheduler
)
# you can sub in any sampler of choice in the line below:
scheduler = DPMSolverMultistepScheduler.from_pretrained("./model", subfolder="scheduler")

#loading the custom pipeline allows for attention emphasis with brackets, and I believe for longer than 77 tokens
pipe = StableDiffusionOnnxPipeline.from_pretrained(
    './model',
    custom_pipeline="lpw_stable_diffusion_onnx",
    revision="onnx",
    scheduler=scheduler,
    safety_checker=None,
    provider="CPUExecutionProvider"
)


prompt = "ethereal landscape"
neg_prompt = ""
                                                                                                                       
generator = torch.Generator(device="cpu").manual_seed(1)


image = pipe.text2img(prompt,negative_prompt=neg_prompt, num_inference_steps=8, width=256, height=256, guidance_scale=10, generator=generator, max_embeddings_multiples=3).images[0]
image.save('./test.png')
```

**Comment by ClashSAN** [comment]
the script above is for running an onnx model, with your model components in the folder ./model, in the current directory. you can convert a diffusers model to onnx with

    python convert_stable_diffusion_checkpoint_to_onnx.py --model_path="runwayml/stable-diffusion-v1-5" --output_path="./model"
this downloads stable-diffusion-v1-5 diffusers model from huggingface, converts the model components: vae(encoder, decoder), unet, text-encoder(clip)  and puts them into a local directory.
