### ISSUE TITLE
Question: does deepsparse engine have own op library for different instruction set like oneDNN and FBGEMM?

### ISSUE THREAD

**Issue by NaNAGISaSA** [neuralmagic/deepsparse#801]
Hello, I notice that the deepsparse engine has achieved an amazing speed for the model after applying your pruning and quantization algorithms. I read the code and find that for deepsparse engine, it loads the module in `deepsparse_engine.so` and then calls methods in it to do inference.
I want to know for the ops in the model after pruning and/or quantization, for example, conv2d and gemm, does deepsparse engine have its own op library for different instruction set like oneDNN and FBGEMM(perhaps in `libdeepsparse.so`)? Thank you!

**Comment by mgoin** [comment]
Hi @NaNAGISaSA yes DeepSparse has its own library of implementations for sparse Conv and MatMul/GEMM operations, which are closed-source in the module.
