### ISSUE TITLE
Assuming I am using a framework like pytorch-geometric or DGL, can deepsparse be applied for accelerating GNNs on CPUs ?

### ISSUE THREAD

**Issue by whiz-Tuhin** [neuralmagic/deepsparse#823]
### Discussed in https://github.com/neuralmagic/deepsparse/discussions/822

<div type='discussions-op-text'>

<sup>Originally posted by **whiz-Tuhin** December 20, 2022</sup>
Hi deepsparse community,

I stumbled on the project through [this](https://www.youtube.com/watch?v=0PAiQ1jTN5k) video. 
I've recently been learning about Graph Neural Networks (GNNs) and wondered if deepsparse can be used to develop GNNs (learning or inference) on CPUs.

Looking forward to your response.

Regards
</div>

**Comment by rahul-tuli** [comment]
Hi @whiz-Tuhin, thanks for reaching out, right now, `deepsparse` only supports inference, your best bet would be to convert the final checkpoint to `onnx`, and then run `deepsparse.benchmark` on it, this would print out `fraction_of_supported_ops` which is a good indication of how much of the network is supported by `deepsparse`
