### ISSUE TITLE
when will macos supported?

### ISSUE THREAD

**Issue by jinfagang** [neuralmagic/deepsparse#853]
OSError: Native Mac is currently unsupported for DeepSparse. Please run on a Linux system or within a Linux container on Mac. More info can be found in our docs here: https://docs.neuralmagic.com/deepsparse/source/hardware.html

**Comment by mgoin** [comment]
Hi @jinfagang DeepSparse is not supported on native Mac or Windows operating systems. We recommend running in a Docker environment, virtual machine, or WSL on Windows. These all allow you to run an Linux environment.

**Comment by jinfagang** [comment]
@mgoin  hello, I know it was not support, but this didn't answer my question.

Will it supported in the future? If so, when?
