### ISSUE TITLE
Exported quantized model running slower than the pruned model on AVX2 supported CPU

### ISSUE THREAD

**Issue by VikasOjha666** [neuralmagic/deepsparse#877]
**Describe the bug**
I have created a library using sparseml and deepsparse for optimizing YOLO v7. After pruning the model is faster than the torch model when inference on the same CPU. However when I created a quantization recipe and exported the model the mode size also got reduced and it accepts uint8 as output but the model is slower than the pruned model. The CPU on which I was running supports int8 inference.

**Expected behavior**
It should be faster than the pruned model since it's both pruned and quantized.

**Environment**
Include all relevant environmental information:
1. OS: Ubuntu 18.04
2. Python version: 3.8.10
3. DeepSparse version: 1.3
4. ML framework version(s) [e.g. torch 1.7.1]: torch 1.9
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:Sparseml==1.3
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
```
{'L1_data_cache_size': 32768, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 262144, 'L3_cache_size': 57671680, 'architecture': 'x86_64', 'available_cores_per_socket': 1, 'available_num_cores': 1, 'available_num_hw_threads': 2, 'available_num_numa': 1, 'available_num_sockets': 1, 'available_sockets': 1, 'available_threads_per_core': 2, 'bf16': False, 'cores_per_socket': 1, 'dotprod': False, 'i8mm': False, 'isa': 'avx2', 'num_cores': 1, 'num_hw_threads': 2, 'num_numa': 1, 'num_sockets': 1, 'threads_per_core': 2, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': 'Intel(R) Xeon(R) CPU @ 2.20GHz', 'vnni': False}

**To Reproduce**
Run the notebook in the attached zip. It contains recipe for both YOLO v7 tiny and base model.
**Errors**
There were no error.

[yolo_v7_sparseml.zip](https://github.com/neuralmagic/deepsparse/files/10482753/yolo_v7_sparseml.zip)

@corey-nm @bfineran @tlrmchlsmth @mgoin

**Comment by mgoin** [comment]
Hi @VikasOjha666 it is difficult to say what is issue is without more detail on the final models produce. Going head-to-head, pruning can offer more speedup than quantization in some cases so if you are comparing an FP32 pruned vs INT8 dense and the pruned model is faster, this shouldn't be a bug. If you have an INT8 pruned model that is slower, then there is likely a bug or the model was quantized in an incorrect way. Can you share any ONNX files from your experiments?

**Comment by VikasOjha666** [comment]
Hi @mgoin . First of all thanks for taking out time and responding. I was trying to compare the int8 pruned model vs the fp32 pruned model and the fp32 model was running fast taking 15s while int8 pruned model takes around 20s for 100 runs. The code and recipes to create the model are provided in the above zip file. For your reference this zip file contains the onnx file for both fp 32 pruned and int8 pruned model. https://drive.google.com/file/d/1amapkB9jIVHYrp7pnzbRhXxiXMpr8xgz/view?usp=share_link

**Comment by VikasOjha666** [comment]
@mgoin Did you found any bug?

**Comment by mgoin** [comment]
Hi @VikasOjha666 thanks for the additional detail! Looking at the quantized ONNX we can see the quantized operations are a bit different than what we recommend for best performance. The quantized inputs to the concats and quantized conv outputs are a bit strange to see. 

<img width="300" alt="Screenshot 2023-01-26 at 3 45 02 PM (1)" src="https://user-images.githubusercontent.com/3195154/215152384-b3dd8eec-941a-4a54-accf-af28d3dd489c.png">

At a first glance, we would recommend adding these arguments to the quantization modifier and re-try exporting through SparseML's exporter:
```yaml
        quantize_linear_activations: false
        quantize_conv_activations: false
        exclude_module_types: [‘LeakyReLU’]
        custom_quantizable_module_types: [‘LeakyReLU’] 
```

Also since you are on an x86 machine without native quantized arithmetic support, you could boost performance of the emulated quantization through enabling `NM_FAST_VNNI_EMULATION=1` at the possible expense of accuracy from integer overflow.

**Comment by VikasOjha666** [comment]
@mgoin . Thanks for taking out time and doing through analysis will try it and let you know the results soon.

**Comment by VikasOjha666** [comment]
@mgoin Tried doing the same as suggested above. It improved the model performance more than before but the model is still slow as compared to the pruned model. I have exported the model with the sparseML ModuleExporter class only. For your reference, I am providing my notebook,recipe and all three models ie. pruned,quantized and quantized_new created as a results of the suggestion in a zip file which can be found at this link https://drive.google.com/file/d/1ZR2axvfZ_Zmdzb3JyyjZhFx1YJDYl4A6/view?usp=share_link . YOLO V3 quantized model available in the sparse zoo runs around 3.8x faster than the torch model on the same CPU. So I am wondering what I am doing wrong.

**Comment by VikasOjha666** [comment]
@mgoin Could you provide any additional hints on how I can proceed further?

**Comment by mgoin** [comment]
HI @VikasOjha666 apologies for the delay. We don't see anything out of place with the quantized graph now, thanks for working in the fixes and sharing your work. 
There is the final convolution that isn't quantized and the QDQ around the leaky relus are strange, but shouldn't be that big of an issue. I do see that there are more data movement operations happening in the quantized model so it is likely up to some tuning that needs to happen within the engine. 
If you can connect with me in our slack about the importance of this model for you, we could work together on improving quantization. Thank you for sharing the nice work!

**Comment by VikasOjha666** [comment]
Hi @mgoin. Thanks for taking time for replying. Actually I have no personal need for working on the model and this was explicitly done for the community. So if some future improvement comes in the engine I will make changes accordingly so that it will be useful for the community.

**Comment by mgoin** [comment]
Thanks Vikas!
