### ISSUE TITLE
Any workplan for supporting ARM CPUs

### ISSUE THREAD

**Issue by iamweiweishi** [neuralmagic/deepsparse#88]
Great contribution. 
It would be better if deepsparse could support ARM devices.

**Comment by markurtz** [comment]
Hi @iamweiweishi, we feel the same way and this is something on our medium-term roadmap! We don't have an exact time frame right now but are actively looking into it. The good news is that the ARM architecture lends itself very well to what we did for the x86 architecture, so we expect similar speedups for pruned and pruned quantized models. We'll be sure to update here once an alpha version is available.

Thanks,
Mark

**Comment by iamweiweishi** [comment]
@markurtz Looking forward to update. Thank you

**Comment by jeanniefinks** [comment]
@iamweiweishi we'll close this issue for now but any arm updates, we'll post back for sure.
