### ISSUE TITLE
Benchmark/Throughput Speed with low CPU core number

### ISSUE THREAD

**Issue by briliantnugraha** [neuralmagic/deepsparse#919]
Hi, thanks for the great for to enable comparable speed to GPU on CPU devices.
This repo has been on my watch list ever since. I've seen a couple of benchmarks in [here](https://neuralmagic.com/blog/benchmark-yolov5-on-cpus-with-deepsparse/), [here](https://neuralmagic.com/blog/yolov8-detection-10x-faster-with-deepsparse-500-fps-on-a-cpu/), and so on.

I am wondering, is there a benchmark with low CPU core number on various GPU type? will the constrained device (low CPU core-N) still as good (or slightly worse) as the high CPU core-N device? 
Because so far, I only see benchmark with 24 core CPU, and those devices are quite pricy by itself(Intel xeon/i9-13900/ryzen 3960 etc).

If it is, it will be a big breakthrough in enabling low-latency inference, performance-wattage/cost saving, and many more!

**Comment by mgoin** [comment]
Hi @briliantnugraha thanks for the interest! Yes, deepsparse does in fact run very well on low-core CPUs. In fact the performance scaling is usually linear with small N cores. I'll share some resources where we have low-core benchmarks.

First, here is a great third-party benchmarking site powered by the Phoronix Test Suite, which deepsparse is a part of: https://openbenchmarking.org/test/pts/deepsparse

Here is a Sparse BioBERT blog processing almost 7000 tokens per second on a 2 core instance: https://neuralmagic.com/blog/revolutionizing-biology-research-with-lightning-fast-nlp-introducing-sparse-biobert/

Here is an image segmentation blog running YOLACT at 20 FPS on a 4 core laptop: https://neuralmagic.com/blog/real-time-instance-segmentation-with-sparse-yolact-on-a-laptop/

Here is deepsparse running on Huggingface Inference Endpoints using just a single core CPU for great cost-savings: https://neuralmagic.com/blog/accelerate-hugging-face-inference-endpoints-with-deepsparse/

**Comment by briliantnugraha** [comment]
Got it, thanks a lot for the detailed references. I will close the issue now~
