### ISSUE TITLE
Pip wheels not updated

### ISSUE THREAD

**Issue by maheshs11** [neuralmagic/deepsparse#938]
Pip wheels deepsparse[server] not updated.

**Comment by markurtz** [comment]
Hi @maheshs11, could you provide more detail on what isn't updating or failing for you?

**Comment by maheshs11** [comment]
> Hi @maheshs11, could you provide more detail on what isn't updating or failing for you?
AttributeError: 'Depends' object has no attribute 'get'

**Comment by maheshs11** [comment]
installed the wheel from GitHub it works fine, but the wheel from pip it's not updated.
