### ISSUE TITLE
DeepSparse: Crash error of compile_model with custom Onnx model

### ISSUE THREAD

**Issue by tttran-cimmi** [neuralmagic/deepsparse#942]
**Describe the bug**
I used sparseml to export torch model to onnx. Then I want to run the onnx by deepspare, but i met the error of Assertion at ./src/include/wand/engine/debug.hpp:233. Please see the log for the detail

**Expected behavior**
I should pass and run the model inference

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 20.04]:
2. Python version [e.g. 3.8]: python 3.8.10
3. DeepSparse version or commit hash [e.g. 0.1.0, `f7245c8`]: 1.4.0
4. ML framework version(s) [e.g. torch 1.7.1]: torch 1.7.1+cu110
5. Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]: onnx 1.12, 
6. CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:
```python
>>> import deepsparse.cpu
>>> print(deepsparse.cpu.cpu_architecture())
```
{'L1_data_cache_size': 32768, 'L1_instruction_cache_size': 32768, 'L2_cache_size': 262144, 'L3_cache_size': 8388608, 'architecture': 'x86_64', 'available_cores_per_socket': 4, 'available_num_cores': 4, 'available_num_hw_threads': 8, 'available_num_numa': 1, 'available_num_sockets': 1, 'available_sockets': 1, 'available_threads_per_core': 2, 'bf16': False, 'cores_per_socket': 4, 'dotprod': False, 'i8mm': False, 'isa': 'avx2', 'num_cores': 4, 'num_hw_threads': 8, 'num_numa': 1, 'num_sockets': 1, 'threads_per_core': 2, 'vendor': 'GenuineIntel', 'vendor_id': 'Intel', 'vendor_model': 'Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz', 'vnni': False}

**To Reproduce**
            from deepsparse import compile_model
            from deepsparse.utils import generate_random_inputs
            
            onnx_filepath = onnx_model_file + "/model.onnx"
            print("==>> onnx_filepath: ", onnx_filepath)
                                               
            print("== Compile model.")                 
            engine = compile_model(onnx_filepath, batch_size=1)
            
            # input [1,3,512,512]
            inputs = generate_random_inputs(onnx_filepath, batch_size=1)
            outputs = engine.run(inputs)

**Errors**

DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.4.0 COMMUNITY | (3be6be5f) (release) (optimized) (system=avx2, binary=avx2)
DeepSparse, Copyright 2021-present / Neuralmagic, Inc. version: 1.4.0 (3be6be5f) (release) (optimized) (system=avx2, binary=avx2)
Date: 03-07-2023 @ 12:05:25 EST
OS: Linux 5.15.0-60-generic #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023
Arch: x86_64
ISA: x86_64-avx2-32-64-16-64-xbyak
CPU: GenuineIntel
Vendor: Intel
Cores/sockets/threads: [4, 1, 8]
Available cores/sockets/threads: [4, 1, 8]
L1 cache size data/instruction: 32k/32k
L2 cache size: 0.25Mb
L3 cache size: 8Mb
Total memory: 33.2866G
Free memory: 7.17848G

Assertion at ./src/include/wand/engine/debug.hpp:233

Backtrace:
 0# wand::detail::abort_prefix(std::ostream&, char const*, char const*, int, bool, bool, unsigned long) in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 1# 0x00007FE4913D83A4 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 2# 0x00007FE4913D9B34 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 3# 0x00007FE4913D48FD in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 4# 0x00007FE4913D4B92 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 5# 0x00007FE4913D4D43 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 6# 0x00007FE4913D51C8 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 7# 0x00007FE4913D5230 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 8# 0x00007FE4905EB3E7 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
 9# 0x00007FE4905EB9FF in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
10# 0x00007FE49068E3F5 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
11# 0x00007FE4905DDC39 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
12# 0x00007FE4905DEFE1 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
13# 0x00007FE490E2C290 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
14# 0x00007FE490E325AE in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
15# 0x00007FE490E351A7 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
16# 0x00007FE490E357B4 in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
17# 0x00007FE49057A3BE in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
18# 0x00007FE49058420D in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
19# 0x00007FE49054B79D in /xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
20# 0x00007FE49055C965 in /xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libonnxruntime.so.1.12.0
21# deepsparse::ort_engine::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::shared_ptr<wand::parallel::scheduler_factory_t>) in /home/xxxxx/lib/python3.8/site-packages/deepsparse/avx2/libdeepsparse.so
22# 0x00007FE49310A697 in /xxxxx/lib/python3.8/site-packages/deepsparse/avx2/deepsparse_engine.so
23# 0x00007FE493147E76 in /xxxxx/lib/python3.8/site-packages/deepsparse/avx2/deepsparse_engine.so

Please email a copy of this stack trace and any additional information to: support@neuralmagic.com
Aborted

**Additional context**
Model file is uploaded at https://drive.google.com/file/d/1cMwdwxrKfoAS9T-VIKkd__-M8GzqiOo1/view?usp=share_link

**Comment by tlrmchlsmth** [comment]
Hi @tttran-cimmi, thanks for your bug report, and thanks for sharing your onnx file as well. I'll take a look and get back to you.

**Comment by tttran-cimmi** [comment]
I tried with sparsify for my onnx model. It gives an error as well.

![Sparsify error](https://user-images.githubusercontent.com/67113413/223803414-93c11eb2-72c0-4680-84b1-1bb1ac313929.png)

**Comment by tttran-cimmi** [comment]
I used the following code to export my model into onnx:
             from sparseml.pytorch.utils import ModuleExporter
            exporter = ModuleExporter(wrapper, output_dir=onnx_model_file)
            exporter.export_onnx(x, output_names=output_names)

The onnx is visualized correctly by Netron.app

Hope that it gives more details for your debug @tlrmchlsmth . Thanks

**Comment by tlrmchlsmth** [comment]
Hi @tttran-cimmi, I've reproduced the assert, and have a fix for it. I will let you know once it's in the nightly.

**Comment by tlrmchlsmth** [comment]
@tttran-cimmi the fix for this is now in the latest nightly (`1.5.0.20230320`)
