### ISSUE TITLE
deepsparse 1.4.0 does not provide the extra 'yolov8'

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/deepsparse#949]
**Describe the bug**
Installation with yolov8 support doesn't work:
```shell
pip install deepsparse[yolov8]
```
prints
```
deepsparse 1.4.0 does not provide the extra 'yolov8'
```

**To Reproduce**
1. conda create --name test python=3.8 -y
2. conda activate test
3. pip install deepsparse[yolov8]

**Comment by dbogunowicz** [comment]
Hey, @eldarkurtic try `pip install deepsparse[ultralytics]`.
We are aware of the discrepancy, I will discuss internally with the team whether this is something that we want to resolve immediately.

**Comment by dbogunowicz** [comment]
Oh, wait, YOLOv8 support debuts in the `1.5` release.

**Comment by rahul-tuli** [comment]
Damian is correct!

**Comment by markurtz** [comment]
Thanks @eldarkurtic, YOLOv8 is on the nightly currently and will be going out with our next 1.5 release in a few weeks.

**Comment by eldarkurtic** [comment]
maybe we should update the docs to reflect that this pip installation is not yet supported
https://github.com/neuralmagic/deepsparse/tree/main/src/deepsparse/yolov8#:~:text=Installation-,pip%20install%20deepsparse%5Byolov8%5D,-Model%20Format
